/*
 * This file is generated by jOOQ.
*/
package com.vince.boot.demo.webapp.jooq;


import com.vince.boot.demo.webapp.jooq.tables.DBlobStore;
import com.vince.boot.demo.webapp.jooq.tables.DBlobStoreH;
import com.vince.boot.demo.webapp.jooq.tables.DClientApp;
import com.vince.boot.demo.webapp.jooq.tables.DGeoLocal;
import com.vince.boot.demo.webapp.jooq.tables.DOrderJob;
import com.vince.boot.demo.webapp.jooq.tables.DRelClientBlob;
import com.vince.boot.demo.webapp.jooq.tables.DRelClientBlobH;
import com.vince.boot.demo.webapp.jooq.tables.DRelOrderBlob;
import com.vince.boot.demo.webapp.jooq.tables.DRelOrderBlobH;
import com.vince.boot.demo.webapp.jooq.tables.DRelUserBlob;
import com.vince.boot.demo.webapp.jooq.tables.DRelUserBlobH;
import com.vince.boot.demo.webapp.jooq.tables.DRoleFunction;
import com.vince.boot.demo.webapp.jooq.tables.DRoleUser;
import com.vince.boot.demo.webapp.jooq.tables.DSystemProps;
import com.vince.boot.demo.webapp.jooq.tables.DSystemPropsH;
import com.vince.boot.demo.webapp.jooq.tables.DTypeDocument;
import com.vince.boot.demo.webapp.jooq.tables.DUserApp;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling indexes of tables of the <code>demo</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index D_BLOB_STORE_IX_RELATIONSHIP35 = Indexes0.D_BLOB_STORE_IX_RELATIONSHIP35;
    public static final Index D_BLOB_STORE_PRIMARY = Indexes0.D_BLOB_STORE_PRIMARY;
    public static final Index D_BLOB_STORE_H_IX_RELATIONSHIP35 = Indexes0.D_BLOB_STORE_H_IX_RELATIONSHIP35;
    public static final Index D_CLIENT_APP_PRIMARY = Indexes0.D_CLIENT_APP_PRIMARY;
    public static final Index D_GEO_LOCAL_PRIMARY = Indexes0.D_GEO_LOCAL_PRIMARY;
    public static final Index D_ORDER_JOB_IX_RELATIONSHIP28 = Indexes0.D_ORDER_JOB_IX_RELATIONSHIP28;
    public static final Index D_ORDER_JOB_PRIMARY = Indexes0.D_ORDER_JOB_PRIMARY;
    public static final Index D_REL_CLIENT_BLOB_IX_RELATIONSHIP32 = Indexes0.D_REL_CLIENT_BLOB_IX_RELATIONSHIP32;
    public static final Index D_REL_CLIENT_BLOB_IX_RELATIONSHIP33 = Indexes0.D_REL_CLIENT_BLOB_IX_RELATIONSHIP33;
    public static final Index D_REL_CLIENT_BLOB_PRIMARY = Indexes0.D_REL_CLIENT_BLOB_PRIMARY;
    public static final Index D_REL_CLIENT_BLOB_H_IX_RELATIONSHIP32 = Indexes0.D_REL_CLIENT_BLOB_H_IX_RELATIONSHIP32;
    public static final Index D_REL_CLIENT_BLOB_H_IX_RELATIONSHIP33 = Indexes0.D_REL_CLIENT_BLOB_H_IX_RELATIONSHIP33;
    public static final Index D_REL_ORDER_BLOB_IX_RELATIONSHIP30 = Indexes0.D_REL_ORDER_BLOB_IX_RELATIONSHIP30;
    public static final Index D_REL_ORDER_BLOB_IX_RELATIONSHIP31 = Indexes0.D_REL_ORDER_BLOB_IX_RELATIONSHIP31;
    public static final Index D_REL_ORDER_BLOB_PRIMARY = Indexes0.D_REL_ORDER_BLOB_PRIMARY;
    public static final Index D_REL_ORDER_BLOB_H_IX_RELATIONSHIP30 = Indexes0.D_REL_ORDER_BLOB_H_IX_RELATIONSHIP30;
    public static final Index D_REL_ORDER_BLOB_H_IX_RELATIONSHIP31 = Indexes0.D_REL_ORDER_BLOB_H_IX_RELATIONSHIP31;
    public static final Index D_REL_USER_BLOB_IX_RELATIONSHIP20 = Indexes0.D_REL_USER_BLOB_IX_RELATIONSHIP20;
    public static final Index D_REL_USER_BLOB_IX_RELATIONSHIP22 = Indexes0.D_REL_USER_BLOB_IX_RELATIONSHIP22;
    public static final Index D_REL_USER_BLOB_PRIMARY = Indexes0.D_REL_USER_BLOB_PRIMARY;
    public static final Index D_REL_USER_BLOB_H_IX_RELATIONSHIP20 = Indexes0.D_REL_USER_BLOB_H_IX_RELATIONSHIP20;
    public static final Index D_REL_USER_BLOB_H_IX_RELATIONSHIP22 = Indexes0.D_REL_USER_BLOB_H_IX_RELATIONSHIP22;
    public static final Index D_ROLE_FUNCTION_PRIMARY = Indexes0.D_ROLE_FUNCTION_PRIMARY;
    public static final Index D_ROLE_USER_PRIMARY = Indexes0.D_ROLE_USER_PRIMARY;
    public static final Index D_ROLE_USER_ROLE = Indexes0.D_ROLE_USER_ROLE;
    public static final Index D_SYSTEM_PROPS_KEY_PROP = Indexes0.D_SYSTEM_PROPS_KEY_PROP;
    public static final Index D_SYSTEM_PROPS_PRIMARY = Indexes0.D_SYSTEM_PROPS_PRIMARY;
    public static final Index D_SYSTEM_PROPS_H_KEY_PROP = Indexes0.D_SYSTEM_PROPS_H_KEY_PROP;
    public static final Index D_SYSTEM_PROPS_H_PRIMARY = Indexes0.D_SYSTEM_PROPS_H_PRIMARY;
    public static final Index D_TYPE_DOCUMENT_PRIMARY = Indexes0.D_TYPE_DOCUMENT_PRIMARY;
    public static final Index D_TYPE_DOCUMENT_ROLE = Indexes0.D_TYPE_DOCUMENT_ROLE;
    public static final Index D_USER_APP_IX_RELATIONSHIP6 = Indexes0.D_USER_APP_IX_RELATIONSHIP6;
    public static final Index D_USER_APP_PRIMARY = Indexes0.D_USER_APP_PRIMARY;
    public static final Index D_USER_APP_USERNAME = Indexes0.D_USER_APP_USERNAME;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index D_BLOB_STORE_IX_RELATIONSHIP35 = createIndex("IX_Relationship35", DBlobStore.D_BLOB_STORE, new OrderField[] { DBlobStore.D_BLOB_STORE.FK_ID_TYPE }, false);
        public static Index D_BLOB_STORE_PRIMARY = createIndex("PRIMARY", DBlobStore.D_BLOB_STORE, new OrderField[] { DBlobStore.D_BLOB_STORE.ID }, true);
        public static Index D_BLOB_STORE_H_IX_RELATIONSHIP35 = createIndex("IX_Relationship35", DBlobStoreH.D_BLOB_STORE_H, new OrderField[] { DBlobStoreH.D_BLOB_STORE_H.FK_ID_TYPE }, false);
        public static Index D_CLIENT_APP_PRIMARY = createIndex("PRIMARY", DClientApp.D_CLIENT_APP, new OrderField[] { DClientApp.D_CLIENT_APP.ID }, true);
        public static Index D_GEO_LOCAL_PRIMARY = createIndex("PRIMARY", DGeoLocal.D_GEO_LOCAL, new OrderField[] { DGeoLocal.D_GEO_LOCAL.ID }, true);
        public static Index D_ORDER_JOB_IX_RELATIONSHIP28 = createIndex("IX_Relationship28", DOrderJob.D_ORDER_JOB, new OrderField[] { DOrderJob.D_ORDER_JOB.FK_ID_CLIENT }, false);
        public static Index D_ORDER_JOB_PRIMARY = createIndex("PRIMARY", DOrderJob.D_ORDER_JOB, new OrderField[] { DOrderJob.D_ORDER_JOB.ID }, true);
        public static Index D_REL_CLIENT_BLOB_IX_RELATIONSHIP32 = createIndex("IX_Relationship32", DRelClientBlob.D_REL_CLIENT_BLOB, new OrderField[] { DRelClientBlob.D_REL_CLIENT_BLOB.FK_ID_CLIENT }, false);
        public static Index D_REL_CLIENT_BLOB_IX_RELATIONSHIP33 = createIndex("IX_Relationship33", DRelClientBlob.D_REL_CLIENT_BLOB, new OrderField[] { DRelClientBlob.D_REL_CLIENT_BLOB.FK_ID_BLOB }, false);
        public static Index D_REL_CLIENT_BLOB_PRIMARY = createIndex("PRIMARY", DRelClientBlob.D_REL_CLIENT_BLOB, new OrderField[] { DRelClientBlob.D_REL_CLIENT_BLOB.ID }, true);
        public static Index D_REL_CLIENT_BLOB_H_IX_RELATIONSHIP32 = createIndex("IX_Relationship32", DRelClientBlobH.D_REL_CLIENT_BLOB_H, new OrderField[] { DRelClientBlobH.D_REL_CLIENT_BLOB_H.FK_ID_CLIENT }, false);
        public static Index D_REL_CLIENT_BLOB_H_IX_RELATIONSHIP33 = createIndex("IX_Relationship33", DRelClientBlobH.D_REL_CLIENT_BLOB_H, new OrderField[] { DRelClientBlobH.D_REL_CLIENT_BLOB_H.FK_ID_BLOB }, false);
        public static Index D_REL_ORDER_BLOB_IX_RELATIONSHIP30 = createIndex("IX_Relationship30", DRelOrderBlob.D_REL_ORDER_BLOB, new OrderField[] { DRelOrderBlob.D_REL_ORDER_BLOB.FK_ID_ORDER }, false);
        public static Index D_REL_ORDER_BLOB_IX_RELATIONSHIP31 = createIndex("IX_Relationship31", DRelOrderBlob.D_REL_ORDER_BLOB, new OrderField[] { DRelOrderBlob.D_REL_ORDER_BLOB.FK_ID_BLOB }, false);
        public static Index D_REL_ORDER_BLOB_PRIMARY = createIndex("PRIMARY", DRelOrderBlob.D_REL_ORDER_BLOB, new OrderField[] { DRelOrderBlob.D_REL_ORDER_BLOB.ID }, true);
        public static Index D_REL_ORDER_BLOB_H_IX_RELATIONSHIP30 = createIndex("IX_Relationship30", DRelOrderBlobH.D_REL_ORDER_BLOB_H, new OrderField[] { DRelOrderBlobH.D_REL_ORDER_BLOB_H.FK_ID_ORDER }, false);
        public static Index D_REL_ORDER_BLOB_H_IX_RELATIONSHIP31 = createIndex("IX_Relationship31", DRelOrderBlobH.D_REL_ORDER_BLOB_H, new OrderField[] { DRelOrderBlobH.D_REL_ORDER_BLOB_H.FK_ID_BLOB }, false);
        public static Index D_REL_USER_BLOB_IX_RELATIONSHIP20 = createIndex("IX_Relationship20", DRelUserBlob.D_REL_USER_BLOB, new OrderField[] { DRelUserBlob.D_REL_USER_BLOB.FK_ID_BLOB }, false);
        public static Index D_REL_USER_BLOB_IX_RELATIONSHIP22 = createIndex("IX_Relationship22", DRelUserBlob.D_REL_USER_BLOB, new OrderField[] { DRelUserBlob.D_REL_USER_BLOB.FK_ID_USER }, false);
        public static Index D_REL_USER_BLOB_PRIMARY = createIndex("PRIMARY", DRelUserBlob.D_REL_USER_BLOB, new OrderField[] { DRelUserBlob.D_REL_USER_BLOB.ID }, true);
        public static Index D_REL_USER_BLOB_H_IX_RELATIONSHIP20 = createIndex("IX_Relationship20", DRelUserBlobH.D_REL_USER_BLOB_H, new OrderField[] { DRelUserBlobH.D_REL_USER_BLOB_H.FK_ID_BLOB }, false);
        public static Index D_REL_USER_BLOB_H_IX_RELATIONSHIP22 = createIndex("IX_Relationship22", DRelUserBlobH.D_REL_USER_BLOB_H, new OrderField[] { DRelUserBlobH.D_REL_USER_BLOB_H.FK_ID_USER }, false);
        public static Index D_ROLE_FUNCTION_PRIMARY = createIndex("PRIMARY", DRoleFunction.D_ROLE_FUNCTION, new OrderField[] { DRoleFunction.D_ROLE_FUNCTION.ID }, true);
        public static Index D_ROLE_USER_PRIMARY = createIndex("PRIMARY", DRoleUser.D_ROLE_USER, new OrderField[] { DRoleUser.D_ROLE_USER.ID }, true);
        public static Index D_ROLE_USER_ROLE = createIndex("role", DRoleUser.D_ROLE_USER, new OrderField[] { DRoleUser.D_ROLE_USER.ROLE_CODE }, true);
        public static Index D_SYSTEM_PROPS_KEY_PROP = createIndex("key_prop", DSystemProps.D_SYSTEM_PROPS, new OrderField[] { DSystemProps.D_SYSTEM_PROPS.KEY_PROP }, true);
        public static Index D_SYSTEM_PROPS_PRIMARY = createIndex("PRIMARY", DSystemProps.D_SYSTEM_PROPS, new OrderField[] { DSystemProps.D_SYSTEM_PROPS.ID }, true);
        public static Index D_SYSTEM_PROPS_H_KEY_PROP = createIndex("key_prop", DSystemPropsH.D_SYSTEM_PROPS_H, new OrderField[] { DSystemPropsH.D_SYSTEM_PROPS_H.KEY_PROP }, true);
        public static Index D_SYSTEM_PROPS_H_PRIMARY = createIndex("PRIMARY", DSystemPropsH.D_SYSTEM_PROPS_H, new OrderField[] { DSystemPropsH.D_SYSTEM_PROPS_H.ID }, true);
        public static Index D_TYPE_DOCUMENT_PRIMARY = createIndex("PRIMARY", DTypeDocument.D_TYPE_DOCUMENT, new OrderField[] { DTypeDocument.D_TYPE_DOCUMENT.ID }, true);
        public static Index D_TYPE_DOCUMENT_ROLE = createIndex("role", DTypeDocument.D_TYPE_DOCUMENT, new OrderField[] { DTypeDocument.D_TYPE_DOCUMENT.TYPE_CODE }, true);
        public static Index D_USER_APP_IX_RELATIONSHIP6 = createIndex("IX_Relationship6", DUserApp.D_USER_APP, new OrderField[] { DUserApp.D_USER_APP.FK_ID_ROLE_USER }, false);
        public static Index D_USER_APP_PRIMARY = createIndex("PRIMARY", DUserApp.D_USER_APP, new OrderField[] { DUserApp.D_USER_APP.ID }, true);
        public static Index D_USER_APP_USERNAME = createIndex("username", DUserApp.D_USER_APP, new OrderField[] { DUserApp.D_USER_APP.USERNAME }, true);
    }
}
