/*
 * This file is generated by jOOQ.
*/
package com.vince.boot.demo.webapp.jooq;


import com.vince.boot.demo.webapp.jooq.tables.DBlobStore;
import com.vince.boot.demo.webapp.jooq.tables.DClientApp;
import com.vince.boot.demo.webapp.jooq.tables.DGeoLocal;
import com.vince.boot.demo.webapp.jooq.tables.DOrderJob;
import com.vince.boot.demo.webapp.jooq.tables.DRelClientBlob;
import com.vince.boot.demo.webapp.jooq.tables.DRelOrderBlob;
import com.vince.boot.demo.webapp.jooq.tables.DRelUserBlob;
import com.vince.boot.demo.webapp.jooq.tables.DRoleFunction;
import com.vince.boot.demo.webapp.jooq.tables.DRoleUser;
import com.vince.boot.demo.webapp.jooq.tables.DSystemProps;
import com.vince.boot.demo.webapp.jooq.tables.DSystemPropsH;
import com.vince.boot.demo.webapp.jooq.tables.DTypeDocument;
import com.vince.boot.demo.webapp.jooq.tables.DUserApp;
import com.vince.boot.demo.webapp.jooq.tables.records.DBlobStoreRecord;
import com.vince.boot.demo.webapp.jooq.tables.records.DClientAppRecord;
import com.vince.boot.demo.webapp.jooq.tables.records.DGeoLocalRecord;
import com.vince.boot.demo.webapp.jooq.tables.records.DOrderJobRecord;
import com.vince.boot.demo.webapp.jooq.tables.records.DRelClientBlobRecord;
import com.vince.boot.demo.webapp.jooq.tables.records.DRelOrderBlobRecord;
import com.vince.boot.demo.webapp.jooq.tables.records.DRelUserBlobRecord;
import com.vince.boot.demo.webapp.jooq.tables.records.DRoleFunctionRecord;
import com.vince.boot.demo.webapp.jooq.tables.records.DRoleUserRecord;
import com.vince.boot.demo.webapp.jooq.tables.records.DSystemPropsHRecord;
import com.vince.boot.demo.webapp.jooq.tables.records.DSystemPropsRecord;
import com.vince.boot.demo.webapp.jooq.tables.records.DTypeDocumentRecord;
import com.vince.boot.demo.webapp.jooq.tables.records.DUserAppRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>demo</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<DBlobStoreRecord, Long> IDENTITY_D_BLOB_STORE = Identities0.IDENTITY_D_BLOB_STORE;
    public static final Identity<DRelClientBlobRecord, Long> IDENTITY_D_REL_CLIENT_BLOB = Identities0.IDENTITY_D_REL_CLIENT_BLOB;
    public static final Identity<DRelOrderBlobRecord, Long> IDENTITY_D_REL_ORDER_BLOB = Identities0.IDENTITY_D_REL_ORDER_BLOB;
    public static final Identity<DRelUserBlobRecord, Long> IDENTITY_D_REL_USER_BLOB = Identities0.IDENTITY_D_REL_USER_BLOB;
    public static final Identity<DUserAppRecord, Long> IDENTITY_D_USER_APP = Identities0.IDENTITY_D_USER_APP;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DBlobStoreRecord> KEY_D_BLOB_STORE_PRIMARY = UniqueKeys0.KEY_D_BLOB_STORE_PRIMARY;
    public static final UniqueKey<DClientAppRecord> KEY_D_CLIENT_APP_PRIMARY = UniqueKeys0.KEY_D_CLIENT_APP_PRIMARY;
    public static final UniqueKey<DGeoLocalRecord> KEY_D_GEO_LOCAL_PRIMARY = UniqueKeys0.KEY_D_GEO_LOCAL_PRIMARY;
    public static final UniqueKey<DOrderJobRecord> KEY_D_ORDER_JOB_PRIMARY = UniqueKeys0.KEY_D_ORDER_JOB_PRIMARY;
    public static final UniqueKey<DRelClientBlobRecord> KEY_D_REL_CLIENT_BLOB_PRIMARY = UniqueKeys0.KEY_D_REL_CLIENT_BLOB_PRIMARY;
    public static final UniqueKey<DRelOrderBlobRecord> KEY_D_REL_ORDER_BLOB_PRIMARY = UniqueKeys0.KEY_D_REL_ORDER_BLOB_PRIMARY;
    public static final UniqueKey<DRelUserBlobRecord> KEY_D_REL_USER_BLOB_PRIMARY = UniqueKeys0.KEY_D_REL_USER_BLOB_PRIMARY;
    public static final UniqueKey<DRoleFunctionRecord> KEY_D_ROLE_FUNCTION_PRIMARY = UniqueKeys0.KEY_D_ROLE_FUNCTION_PRIMARY;
    public static final UniqueKey<DRoleUserRecord> KEY_D_ROLE_USER_PRIMARY = UniqueKeys0.KEY_D_ROLE_USER_PRIMARY;
    public static final UniqueKey<DRoleUserRecord> KEY_D_ROLE_USER_ROLE = UniqueKeys0.KEY_D_ROLE_USER_ROLE;
    public static final UniqueKey<DSystemPropsRecord> KEY_D_SYSTEM_PROPS_PRIMARY = UniqueKeys0.KEY_D_SYSTEM_PROPS_PRIMARY;
    public static final UniqueKey<DSystemPropsRecord> KEY_D_SYSTEM_PROPS_KEY_PROP = UniqueKeys0.KEY_D_SYSTEM_PROPS_KEY_PROP;
    public static final UniqueKey<DSystemPropsHRecord> KEY_D_SYSTEM_PROPS_H_PRIMARY = UniqueKeys0.KEY_D_SYSTEM_PROPS_H_PRIMARY;
    public static final UniqueKey<DSystemPropsHRecord> KEY_D_SYSTEM_PROPS_H_KEY_PROP = UniqueKeys0.KEY_D_SYSTEM_PROPS_H_KEY_PROP;
    public static final UniqueKey<DTypeDocumentRecord> KEY_D_TYPE_DOCUMENT_PRIMARY = UniqueKeys0.KEY_D_TYPE_DOCUMENT_PRIMARY;
    public static final UniqueKey<DTypeDocumentRecord> KEY_D_TYPE_DOCUMENT_ROLE = UniqueKeys0.KEY_D_TYPE_DOCUMENT_ROLE;
    public static final UniqueKey<DUserAppRecord> KEY_D_USER_APP_USERNAME = UniqueKeys0.KEY_D_USER_APP_USERNAME;
    public static final UniqueKey<DUserAppRecord> KEY_D_USER_APP_PRIMARY = UniqueKeys0.KEY_D_USER_APP_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<DBlobStoreRecord, DTypeDocumentRecord> RELATIONSHIP35 = ForeignKeys0.RELATIONSHIP35;
    public static final ForeignKey<DOrderJobRecord, DClientAppRecord> RELATIONSHIP28 = ForeignKeys0.RELATIONSHIP28;
    public static final ForeignKey<DRelClientBlobRecord, DClientAppRecord> RELATIONSHIP32 = ForeignKeys0.RELATIONSHIP32;
    public static final ForeignKey<DRelClientBlobRecord, DBlobStoreRecord> RELATIONSHIP33 = ForeignKeys0.RELATIONSHIP33;
    public static final ForeignKey<DRelOrderBlobRecord, DOrderJobRecord> RELATIONSHIP30 = ForeignKeys0.RELATIONSHIP30;
    public static final ForeignKey<DRelOrderBlobRecord, DBlobStoreRecord> RELATIONSHIP31 = ForeignKeys0.RELATIONSHIP31;
    public static final ForeignKey<DRelUserBlobRecord, DUserAppRecord> RELATIONSHIP22 = ForeignKeys0.RELATIONSHIP22;
    public static final ForeignKey<DRelUserBlobRecord, DBlobStoreRecord> RELATIONSHIP20 = ForeignKeys0.RELATIONSHIP20;
    public static final ForeignKey<DRoleFunctionRecord, DRoleUserRecord> RELATIONSHIP8 = ForeignKeys0.RELATIONSHIP8;
    public static final ForeignKey<DUserAppRecord, DRoleUserRecord> RELATIONSHIP6 = ForeignKeys0.RELATIONSHIP6;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<DBlobStoreRecord, Long> IDENTITY_D_BLOB_STORE = createIdentity(DBlobStore.D_BLOB_STORE, DBlobStore.D_BLOB_STORE.ID);
        public static Identity<DRelClientBlobRecord, Long> IDENTITY_D_REL_CLIENT_BLOB = createIdentity(DRelClientBlob.D_REL_CLIENT_BLOB, DRelClientBlob.D_REL_CLIENT_BLOB.ID);
        public static Identity<DRelOrderBlobRecord, Long> IDENTITY_D_REL_ORDER_BLOB = createIdentity(DRelOrderBlob.D_REL_ORDER_BLOB, DRelOrderBlob.D_REL_ORDER_BLOB.ID);
        public static Identity<DRelUserBlobRecord, Long> IDENTITY_D_REL_USER_BLOB = createIdentity(DRelUserBlob.D_REL_USER_BLOB, DRelUserBlob.D_REL_USER_BLOB.ID);
        public static Identity<DUserAppRecord, Long> IDENTITY_D_USER_APP = createIdentity(DUserApp.D_USER_APP, DUserApp.D_USER_APP.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<DBlobStoreRecord> KEY_D_BLOB_STORE_PRIMARY = createUniqueKey(DBlobStore.D_BLOB_STORE, "KEY_d_blob_store_PRIMARY", DBlobStore.D_BLOB_STORE.ID);
        public static final UniqueKey<DClientAppRecord> KEY_D_CLIENT_APP_PRIMARY = createUniqueKey(DClientApp.D_CLIENT_APP, "KEY_d_client_app_PRIMARY", DClientApp.D_CLIENT_APP.ID);
        public static final UniqueKey<DGeoLocalRecord> KEY_D_GEO_LOCAL_PRIMARY = createUniqueKey(DGeoLocal.D_GEO_LOCAL, "KEY_d_geo_local_PRIMARY", DGeoLocal.D_GEO_LOCAL.ID);
        public static final UniqueKey<DOrderJobRecord> KEY_D_ORDER_JOB_PRIMARY = createUniqueKey(DOrderJob.D_ORDER_JOB, "KEY_d_order_job_PRIMARY", DOrderJob.D_ORDER_JOB.ID);
        public static final UniqueKey<DRelClientBlobRecord> KEY_D_REL_CLIENT_BLOB_PRIMARY = createUniqueKey(DRelClientBlob.D_REL_CLIENT_BLOB, "KEY_d_rel_client_blob_PRIMARY", DRelClientBlob.D_REL_CLIENT_BLOB.ID);
        public static final UniqueKey<DRelOrderBlobRecord> KEY_D_REL_ORDER_BLOB_PRIMARY = createUniqueKey(DRelOrderBlob.D_REL_ORDER_BLOB, "KEY_d_rel_order_blob_PRIMARY", DRelOrderBlob.D_REL_ORDER_BLOB.ID);
        public static final UniqueKey<DRelUserBlobRecord> KEY_D_REL_USER_BLOB_PRIMARY = createUniqueKey(DRelUserBlob.D_REL_USER_BLOB, "KEY_d_rel_user_blob_PRIMARY", DRelUserBlob.D_REL_USER_BLOB.ID);
        public static final UniqueKey<DRoleFunctionRecord> KEY_D_ROLE_FUNCTION_PRIMARY = createUniqueKey(DRoleFunction.D_ROLE_FUNCTION, "KEY_d_role_function_PRIMARY", DRoleFunction.D_ROLE_FUNCTION.ID);
        public static final UniqueKey<DRoleUserRecord> KEY_D_ROLE_USER_PRIMARY = createUniqueKey(DRoleUser.D_ROLE_USER, "KEY_d_role_user_PRIMARY", DRoleUser.D_ROLE_USER.ID);
        public static final UniqueKey<DRoleUserRecord> KEY_D_ROLE_USER_ROLE = createUniqueKey(DRoleUser.D_ROLE_USER, "KEY_d_role_user_role", DRoleUser.D_ROLE_USER.ROLE_CODE);
        public static final UniqueKey<DSystemPropsRecord> KEY_D_SYSTEM_PROPS_PRIMARY = createUniqueKey(DSystemProps.D_SYSTEM_PROPS, "KEY_d_system_props_PRIMARY", DSystemProps.D_SYSTEM_PROPS.ID);
        public static final UniqueKey<DSystemPropsRecord> KEY_D_SYSTEM_PROPS_KEY_PROP = createUniqueKey(DSystemProps.D_SYSTEM_PROPS, "KEY_d_system_props_key_prop", DSystemProps.D_SYSTEM_PROPS.KEY_PROP);
        public static final UniqueKey<DSystemPropsHRecord> KEY_D_SYSTEM_PROPS_H_PRIMARY = createUniqueKey(DSystemPropsH.D_SYSTEM_PROPS_H, "KEY_d_system_props_h_PRIMARY", DSystemPropsH.D_SYSTEM_PROPS_H.ID);
        public static final UniqueKey<DSystemPropsHRecord> KEY_D_SYSTEM_PROPS_H_KEY_PROP = createUniqueKey(DSystemPropsH.D_SYSTEM_PROPS_H, "KEY_d_system_props_h_key_prop", DSystemPropsH.D_SYSTEM_PROPS_H.KEY_PROP);
        public static final UniqueKey<DTypeDocumentRecord> KEY_D_TYPE_DOCUMENT_PRIMARY = createUniqueKey(DTypeDocument.D_TYPE_DOCUMENT, "KEY_d_type_document_PRIMARY", DTypeDocument.D_TYPE_DOCUMENT.ID);
        public static final UniqueKey<DTypeDocumentRecord> KEY_D_TYPE_DOCUMENT_ROLE = createUniqueKey(DTypeDocument.D_TYPE_DOCUMENT, "KEY_d_type_document_role", DTypeDocument.D_TYPE_DOCUMENT.TYPE_CODE);
        public static final UniqueKey<DUserAppRecord> KEY_D_USER_APP_USERNAME = createUniqueKey(DUserApp.D_USER_APP, "KEY_d_user_app_username", DUserApp.D_USER_APP.USERNAME);
        public static final UniqueKey<DUserAppRecord> KEY_D_USER_APP_PRIMARY = createUniqueKey(DUserApp.D_USER_APP, "KEY_d_user_app_PRIMARY", DUserApp.D_USER_APP.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<DBlobStoreRecord, DTypeDocumentRecord> RELATIONSHIP35 = createForeignKey(com.vince.boot.demo.webapp.jooq.Keys.KEY_D_TYPE_DOCUMENT_PRIMARY, DBlobStore.D_BLOB_STORE, "Relationship35", DBlobStore.D_BLOB_STORE.FK_ID_TYPE);
        public static final ForeignKey<DOrderJobRecord, DClientAppRecord> RELATIONSHIP28 = createForeignKey(com.vince.boot.demo.webapp.jooq.Keys.KEY_D_CLIENT_APP_PRIMARY, DOrderJob.D_ORDER_JOB, "Relationship28", DOrderJob.D_ORDER_JOB.FK_ID_CLIENT);
        public static final ForeignKey<DRelClientBlobRecord, DClientAppRecord> RELATIONSHIP32 = createForeignKey(com.vince.boot.demo.webapp.jooq.Keys.KEY_D_CLIENT_APP_PRIMARY, DRelClientBlob.D_REL_CLIENT_BLOB, "Relationship32", DRelClientBlob.D_REL_CLIENT_BLOB.FK_ID_CLIENT);
        public static final ForeignKey<DRelClientBlobRecord, DBlobStoreRecord> RELATIONSHIP33 = createForeignKey(com.vince.boot.demo.webapp.jooq.Keys.KEY_D_BLOB_STORE_PRIMARY, DRelClientBlob.D_REL_CLIENT_BLOB, "Relationship33", DRelClientBlob.D_REL_CLIENT_BLOB.FK_ID_BLOB);
        public static final ForeignKey<DRelOrderBlobRecord, DOrderJobRecord> RELATIONSHIP30 = createForeignKey(com.vince.boot.demo.webapp.jooq.Keys.KEY_D_ORDER_JOB_PRIMARY, DRelOrderBlob.D_REL_ORDER_BLOB, "Relationship30", DRelOrderBlob.D_REL_ORDER_BLOB.FK_ID_ORDER);
        public static final ForeignKey<DRelOrderBlobRecord, DBlobStoreRecord> RELATIONSHIP31 = createForeignKey(com.vince.boot.demo.webapp.jooq.Keys.KEY_D_BLOB_STORE_PRIMARY, DRelOrderBlob.D_REL_ORDER_BLOB, "Relationship31", DRelOrderBlob.D_REL_ORDER_BLOB.FK_ID_BLOB);
        public static final ForeignKey<DRelUserBlobRecord, DUserAppRecord> RELATIONSHIP22 = createForeignKey(com.vince.boot.demo.webapp.jooq.Keys.KEY_D_USER_APP_PRIMARY, DRelUserBlob.D_REL_USER_BLOB, "Relationship22", DRelUserBlob.D_REL_USER_BLOB.FK_ID_USER);
        public static final ForeignKey<DRelUserBlobRecord, DBlobStoreRecord> RELATIONSHIP20 = createForeignKey(com.vince.boot.demo.webapp.jooq.Keys.KEY_D_BLOB_STORE_PRIMARY, DRelUserBlob.D_REL_USER_BLOB, "Relationship20", DRelUserBlob.D_REL_USER_BLOB.FK_ID_BLOB);
        public static final ForeignKey<DRoleFunctionRecord, DRoleUserRecord> RELATIONSHIP8 = createForeignKey(com.vince.boot.demo.webapp.jooq.Keys.KEY_D_ROLE_USER_PRIMARY, DRoleFunction.D_ROLE_FUNCTION, "Relationship8", DRoleFunction.D_ROLE_FUNCTION.ID);
        public static final ForeignKey<DUserAppRecord, DRoleUserRecord> RELATIONSHIP6 = createForeignKey(com.vince.boot.demo.webapp.jooq.Keys.KEY_D_ROLE_USER_PRIMARY, DUserApp.D_USER_APP, "Relationship6", DUserApp.D_USER_APP.FK_ID_ROLE_USER);
    }
}
