/*
 * This file is generated by jOOQ.
*/
package com.vince.boot.demo.webapp.jooq.tables.records;


import com.vince.boot.demo.webapp.jooq.tables.DBlobStore;

import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DBlobStoreRecord extends UpdatableRecordImpl<DBlobStoreRecord> implements Record12<String, String, Timestamp, Timestamp, Long, String, String, byte[], Long, String, String, Date> {

    private static final long serialVersionUID = 1503693836;

    /**
     * Setter for <code>demo.d_blob_store.user_insert</code>.
     */
    public void setUserInsert(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>demo.d_blob_store.user_insert</code>.
     */
    public String getUserInsert() {
        return (String) get(0);
    }

    /**
     * Setter for <code>demo.d_blob_store.user_update</code>.
     */
    public void setUserUpdate(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>demo.d_blob_store.user_update</code>.
     */
    public String getUserUpdate() {
        return (String) get(1);
    }

    /**
     * Setter for <code>demo.d_blob_store.time_insert</code>.
     */
    public void setTimeInsert(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>demo.d_blob_store.time_insert</code>.
     */
    public Timestamp getTimeInsert() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>demo.d_blob_store.time_update</code>.
     */
    public void setTimeUpdate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>demo.d_blob_store.time_update</code>.
     */
    public Timestamp getTimeUpdate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>demo.d_blob_store.id</code>.
     */
    public void setId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>demo.d_blob_store.id</code>.
     */
    public Long getId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>demo.d_blob_store.filename</code>.
     */
    public void setFilename(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>demo.d_blob_store.filename</code>.
     */
    public String getFilename() {
        return (String) get(5);
    }

    /**
     * Setter for <code>demo.d_blob_store.flag_active</code>.
     */
    public void setFlagActive(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>demo.d_blob_store.flag_active</code>.
     */
    public String getFlagActive() {
        return (String) get(6);
    }

    /**
     * Setter for <code>demo.d_blob_store.blob_data</code>.
     */
    public void setBlobData(byte... value) {
        set(7, value);
    }

    /**
     * Getter for <code>demo.d_blob_store.blob_data</code>.
     */
    public byte[] getBlobData() {
        return (byte[]) get(7);
    }

    /**
     * Setter for <code>demo.d_blob_store.fk_id_type</code>.
     */
    public void setFkIdType(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>demo.d_blob_store.fk_id_type</code>.
     */
    public Long getFkIdType() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>demo.d_blob_store.description</code>.
     */
    public void setDescription(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>demo.d_blob_store.description</code>.
     */
    public String getDescription() {
        return (String) get(9);
    }

    /**
     * Setter for <code>demo.d_blob_store.content_type</code>.
     */
    public void setContentType(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>demo.d_blob_store.content_type</code>.
     */
    public String getContentType() {
        return (String) get(10);
    }

    /**
     * Setter for <code>demo.d_blob_store.year_refer</code>.
     */
    public void setYearRefer(Date value) {
        set(11, value);
    }

    /**
     * Getter for <code>demo.d_blob_store.year_refer</code>.
     */
    public Date getYearRefer() {
        return (Date) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<String, String, Timestamp, Timestamp, Long, String, String, byte[], Long, String, String, Date> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<String, String, Timestamp, Timestamp, Long, String, String, byte[], Long, String, String, Date> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return DBlobStore.D_BLOB_STORE.USER_INSERT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DBlobStore.D_BLOB_STORE.USER_UPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return DBlobStore.D_BLOB_STORE.TIME_INSERT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return DBlobStore.D_BLOB_STORE.TIME_UPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return DBlobStore.D_BLOB_STORE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return DBlobStore.D_BLOB_STORE.FILENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return DBlobStore.D_BLOB_STORE.FLAG_ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field8() {
        return DBlobStore.D_BLOB_STORE.BLOB_DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return DBlobStore.D_BLOB_STORE.FK_ID_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return DBlobStore.D_BLOB_STORE.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return DBlobStore.D_BLOB_STORE.CONTENT_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field12() {
        return DBlobStore.D_BLOB_STORE.YEAR_REFER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getUserInsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUserUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getTimeInsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getTimeUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getFilename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getFlagActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component8() {
        return getBlobData();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component9() {
        return getFkIdType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getContentType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component12() {
        return getYearRefer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getUserInsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUserUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getTimeInsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getTimeUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getFilename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getFlagActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value8() {
        return getBlobData();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getFkIdType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getContentType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value12() {
        return getYearRefer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DBlobStoreRecord value1(String value) {
        setUserInsert(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DBlobStoreRecord value2(String value) {
        setUserUpdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DBlobStoreRecord value3(Timestamp value) {
        setTimeInsert(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DBlobStoreRecord value4(Timestamp value) {
        setTimeUpdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DBlobStoreRecord value5(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DBlobStoreRecord value6(String value) {
        setFilename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DBlobStoreRecord value7(String value) {
        setFlagActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DBlobStoreRecord value8(byte... value) {
        setBlobData(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DBlobStoreRecord value9(Long value) {
        setFkIdType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DBlobStoreRecord value10(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DBlobStoreRecord value11(String value) {
        setContentType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DBlobStoreRecord value12(Date value) {
        setYearRefer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DBlobStoreRecord values(String value1, String value2, Timestamp value3, Timestamp value4, Long value5, String value6, String value7, byte[] value8, Long value9, String value10, String value11, Date value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DBlobStoreRecord
     */
    public DBlobStoreRecord() {
        super(DBlobStore.D_BLOB_STORE);
    }

    /**
     * Create a detached, initialised DBlobStoreRecord
     */
    public DBlobStoreRecord(String userInsert, String userUpdate, Timestamp timeInsert, Timestamp timeUpdate, Long id, String filename, String flagActive, byte[] blobData, Long fkIdType, String description, String contentType, Date yearRefer) {
        super(DBlobStore.D_BLOB_STORE);

        set(0, userInsert);
        set(1, userUpdate);
        set(2, timeInsert);
        set(3, timeUpdate);
        set(4, id);
        set(5, filename);
        set(6, flagActive);
        set(7, blobData);
        set(8, fkIdType);
        set(9, description);
        set(10, contentType);
        set(11, yearRefer);
    }
}
