/*
 * This file is generated by jOOQ.
*/
package com.vince.boot.demo.webapp.jooq.tables.records;


import com.vince.boot.demo.webapp.jooq.tables.DClientApp;

import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DClientAppRecord extends UpdatableRecordImpl<DClientAppRecord> implements Record13<String, String, Timestamp, Timestamp, Long, String, String, String, String, String, String, String, Date> {

    private static final long serialVersionUID = -926030132;

    /**
     * Setter for <code>demo.d_client_app.user_insert</code>.
     */
    public void setUserInsert(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>demo.d_client_app.user_insert</code>.
     */
    public String getUserInsert() {
        return (String) get(0);
    }

    /**
     * Setter for <code>demo.d_client_app.user_update</code>.
     */
    public void setUserUpdate(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>demo.d_client_app.user_update</code>.
     */
    public String getUserUpdate() {
        return (String) get(1);
    }

    /**
     * Setter for <code>demo.d_client_app.time_insert</code>.
     */
    public void setTimeInsert(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>demo.d_client_app.time_insert</code>.
     */
    public Timestamp getTimeInsert() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>demo.d_client_app.time_update</code>.
     */
    public void setTimeUpdate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>demo.d_client_app.time_update</code>.
     */
    public Timestamp getTimeUpdate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>demo.d_client_app.id</code>.
     */
    public void setId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>demo.d_client_app.id</code>.
     */
    public Long getId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>demo.d_client_app.name</code>.
     */
    public void setName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>demo.d_client_app.name</code>.
     */
    public String getName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>demo.d_client_app.piva</code>.
     */
    public void setPiva(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>demo.d_client_app.piva</code>.
     */
    public String getPiva() {
        return (String) get(6);
    }

    /**
     * Setter for <code>demo.d_client_app.address</code>.
     */
    public void setAddress(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>demo.d_client_app.address</code>.
     */
    public String getAddress() {
        return (String) get(7);
    }

    /**
     * Setter for <code>demo.d_client_app.zipcode</code>.
     */
    public void setZipcode(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>demo.d_client_app.zipcode</code>.
     */
    public String getZipcode() {
        return (String) get(8);
    }

    /**
     * Setter for <code>demo.d_client_app.notes</code>.
     */
    public void setNotes(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>demo.d_client_app.notes</code>.
     */
    public String getNotes() {
        return (String) get(9);
    }

    /**
     * Setter for <code>demo.d_client_app.phone</code>.
     */
    public void setPhone(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>demo.d_client_app.phone</code>.
     */
    public String getPhone() {
        return (String) get(10);
    }

    /**
     * Setter for <code>demo.d_client_app.email</code>.
     */
    public void setEmail(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>demo.d_client_app.email</code>.
     */
    public String getEmail() {
        return (String) get(11);
    }

    /**
     * Setter for <code>demo.d_client_app.year_refer</code>.
     */
    public void setYearRefer(Date value) {
        set(12, value);
    }

    /**
     * Getter for <code>demo.d_client_app.year_refer</code>.
     */
    public Date getYearRefer() {
        return (Date) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<String, String, Timestamp, Timestamp, Long, String, String, String, String, String, String, String, Date> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<String, String, Timestamp, Timestamp, Long, String, String, String, String, String, String, String, Date> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return DClientApp.D_CLIENT_APP.USER_INSERT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DClientApp.D_CLIENT_APP.USER_UPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return DClientApp.D_CLIENT_APP.TIME_INSERT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return DClientApp.D_CLIENT_APP.TIME_UPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return DClientApp.D_CLIENT_APP.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return DClientApp.D_CLIENT_APP.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return DClientApp.D_CLIENT_APP.PIVA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return DClientApp.D_CLIENT_APP.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return DClientApp.D_CLIENT_APP.ZIPCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return DClientApp.D_CLIENT_APP.NOTES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return DClientApp.D_CLIENT_APP.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return DClientApp.D_CLIENT_APP.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field13() {
        return DClientApp.D_CLIENT_APP.YEAR_REFER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getUserInsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUserUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getTimeInsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getTimeUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getPiva();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getZipcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getNotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component13() {
        return getYearRefer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getUserInsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUserUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getTimeInsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getTimeUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getPiva();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getZipcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getNotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value13() {
        return getYearRefer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DClientAppRecord value1(String value) {
        setUserInsert(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DClientAppRecord value2(String value) {
        setUserUpdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DClientAppRecord value3(Timestamp value) {
        setTimeInsert(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DClientAppRecord value4(Timestamp value) {
        setTimeUpdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DClientAppRecord value5(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DClientAppRecord value6(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DClientAppRecord value7(String value) {
        setPiva(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DClientAppRecord value8(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DClientAppRecord value9(String value) {
        setZipcode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DClientAppRecord value10(String value) {
        setNotes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DClientAppRecord value11(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DClientAppRecord value12(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DClientAppRecord value13(Date value) {
        setYearRefer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DClientAppRecord values(String value1, String value2, Timestamp value3, Timestamp value4, Long value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, Date value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DClientAppRecord
     */
    public DClientAppRecord() {
        super(DClientApp.D_CLIENT_APP);
    }

    /**
     * Create a detached, initialised DClientAppRecord
     */
    public DClientAppRecord(String userInsert, String userUpdate, Timestamp timeInsert, Timestamp timeUpdate, Long id, String name, String piva, String address, String zipcode, String notes, String phone, String email, Date yearRefer) {
        super(DClientApp.D_CLIENT_APP);

        set(0, userInsert);
        set(1, userUpdate);
        set(2, timeInsert);
        set(3, timeUpdate);
        set(4, id);
        set(5, name);
        set(6, piva);
        set(7, address);
        set(8, zipcode);
        set(9, notes);
        set(10, phone);
        set(11, email);
        set(12, yearRefer);
    }
}
