/*
 * This file is generated by jOOQ.
*/
package com.vince.boot.demo.webapp.jooq.tables.records;


import com.vince.boot.demo.webapp.jooq.tables.DOrderJobH;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DOrderJobHRecord extends TableRecordImpl<DOrderJobHRecord> implements Record15<String, String, Timestamp, Timestamp, Long, Long, String, String, Timestamp, Date, BigDecimal, BigDecimal, String, String, byte[]> {

    private static final long serialVersionUID = 502468226;

    /**
     * Setter for <code>demo.d_order_job_h.user_insert</code>.
     */
    public void setUserInsert(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>demo.d_order_job_h.user_insert</code>.
     */
    public String getUserInsert() {
        return (String) get(0);
    }

    /**
     * Setter for <code>demo.d_order_job_h.user_update</code>.
     */
    public void setUserUpdate(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>demo.d_order_job_h.user_update</code>.
     */
    public String getUserUpdate() {
        return (String) get(1);
    }

    /**
     * Setter for <code>demo.d_order_job_h.time_insert</code>.
     */
    public void setTimeInsert(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>demo.d_order_job_h.time_insert</code>.
     */
    public Timestamp getTimeInsert() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>demo.d_order_job_h.time_update</code>.
     */
    public void setTimeUpdate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>demo.d_order_job_h.time_update</code>.
     */
    public Timestamp getTimeUpdate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>demo.d_order_job_h.id</code>.
     */
    public void setId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>demo.d_order_job_h.id</code>.
     */
    public Long getId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>demo.d_order_job_h.fk_id_client</code>.
     */
    public void setFkIdClient(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>demo.d_order_job_h.fk_id_client</code>.
     */
    public Long getFkIdClient() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>demo.d_order_job_h.notes</code>.
     */
    public void setNotes(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>demo.d_order_job_h.notes</code>.
     */
    public String getNotes() {
        return (String) get(6);
    }

    /**
     * Setter for <code>demo.d_order_job_h.code_order</code>.
     */
    public void setCodeOrder(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>demo.d_order_job_h.code_order</code>.
     */
    public String getCodeOrder() {
        return (String) get(7);
    }

    /**
     * Setter for <code>demo.d_order_job_h.data_scadenza</code>.
     */
    public void setDataScadenza(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>demo.d_order_job_h.data_scadenza</code>.
     */
    public Timestamp getDataScadenza() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>demo.d_order_job_h.year_refer</code>.
     */
    public void setYearRefer(Date value) {
        set(9, value);
    }

    /**
     * Getter for <code>demo.d_order_job_h.year_refer</code>.
     */
    public Date getYearRefer() {
        return (Date) get(9);
    }

    /**
     * Setter for <code>demo.d_order_job_h.pre_amount</code>.
     */
    public void setPreAmount(BigDecimal value) {
        set(10, value);
    }

    /**
     * Getter for <code>demo.d_order_job_h.pre_amount</code>.
     */
    public BigDecimal getPreAmount() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>demo.d_order_job_h.final_amount</code>.
     */
    public void setFinalAmount(BigDecimal value) {
        set(11, value);
    }

    /**
     * Getter for <code>demo.d_order_job_h.final_amount</code>.
     */
    public BigDecimal getFinalAmount() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for <code>demo.d_order_job_h.flag_active</code>.
     */
    public void setFlagActive(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>demo.d_order_job_h.flag_active</code>.
     */
    public String getFlagActive() {
        return (String) get(12);
    }

    /**
     * Setter for <code>demo.d_order_job_h.crud_type</code>.
     */
    public void setCrudType(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>demo.d_order_job_h.crud_type</code>.
     */
    public String getCrudType() {
        return (String) get(13);
    }

    /**
     * Setter for <code>demo.d_order_job_h.address</code>.
     */
    public void setAddress(byte... value) {
        set(14, value);
    }

    /**
     * Getter for <code>demo.d_order_job_h.address</code>.
     */
    public byte[] getAddress() {
        return (byte[]) get(14);
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<String, String, Timestamp, Timestamp, Long, Long, String, String, Timestamp, Date, BigDecimal, BigDecimal, String, String, byte[]> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<String, String, Timestamp, Timestamp, Long, Long, String, String, Timestamp, Date, BigDecimal, BigDecimal, String, String, byte[]> valuesRow() {
        return (Row15) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return DOrderJobH.D_ORDER_JOB_H.USER_INSERT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DOrderJobH.D_ORDER_JOB_H.USER_UPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return DOrderJobH.D_ORDER_JOB_H.TIME_INSERT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return DOrderJobH.D_ORDER_JOB_H.TIME_UPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return DOrderJobH.D_ORDER_JOB_H.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return DOrderJobH.D_ORDER_JOB_H.FK_ID_CLIENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return DOrderJobH.D_ORDER_JOB_H.NOTES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return DOrderJobH.D_ORDER_JOB_H.CODE_ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return DOrderJobH.D_ORDER_JOB_H.DATA_SCADENZA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field10() {
        return DOrderJobH.D_ORDER_JOB_H.YEAR_REFER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field11() {
        return DOrderJobH.D_ORDER_JOB_H.PRE_AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field12() {
        return DOrderJobH.D_ORDER_JOB_H.FINAL_AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return DOrderJobH.D_ORDER_JOB_H.FLAG_ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return DOrderJobH.D_ORDER_JOB_H.CRUD_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field15() {
        return DOrderJobH.D_ORDER_JOB_H.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getUserInsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUserUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getTimeInsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getTimeUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getFkIdClient();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getNotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getCodeOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getDataScadenza();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component10() {
        return getYearRefer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component11() {
        return getPreAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component12() {
        return getFinalAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getFlagActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getCrudType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component15() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getUserInsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUserUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getTimeInsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getTimeUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getFkIdClient();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getNotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getCodeOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getDataScadenza();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value10() {
        return getYearRefer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value11() {
        return getPreAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value12() {
        return getFinalAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getFlagActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getCrudType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value15() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DOrderJobHRecord value1(String value) {
        setUserInsert(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DOrderJobHRecord value2(String value) {
        setUserUpdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DOrderJobHRecord value3(Timestamp value) {
        setTimeInsert(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DOrderJobHRecord value4(Timestamp value) {
        setTimeUpdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DOrderJobHRecord value5(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DOrderJobHRecord value6(Long value) {
        setFkIdClient(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DOrderJobHRecord value7(String value) {
        setNotes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DOrderJobHRecord value8(String value) {
        setCodeOrder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DOrderJobHRecord value9(Timestamp value) {
        setDataScadenza(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DOrderJobHRecord value10(Date value) {
        setYearRefer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DOrderJobHRecord value11(BigDecimal value) {
        setPreAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DOrderJobHRecord value12(BigDecimal value) {
        setFinalAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DOrderJobHRecord value13(String value) {
        setFlagActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DOrderJobHRecord value14(String value) {
        setCrudType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DOrderJobHRecord value15(byte... value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DOrderJobHRecord values(String value1, String value2, Timestamp value3, Timestamp value4, Long value5, Long value6, String value7, String value8, Timestamp value9, Date value10, BigDecimal value11, BigDecimal value12, String value13, String value14, byte[] value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DOrderJobHRecord
     */
    public DOrderJobHRecord() {
        super(DOrderJobH.D_ORDER_JOB_H);
    }

    /**
     * Create a detached, initialised DOrderJobHRecord
     */
    public DOrderJobHRecord(String userInsert, String userUpdate, Timestamp timeInsert, Timestamp timeUpdate, Long id, Long fkIdClient, String notes, String codeOrder, Timestamp dataScadenza, Date yearRefer, BigDecimal preAmount, BigDecimal finalAmount, String flagActive, String crudType, byte[] address) {
        super(DOrderJobH.D_ORDER_JOB_H);

        set(0, userInsert);
        set(1, userUpdate);
        set(2, timeInsert);
        set(3, timeUpdate);
        set(4, id);
        set(5, fkIdClient);
        set(6, notes);
        set(7, codeOrder);
        set(8, dataScadenza);
        set(9, yearRefer);
        set(10, preAmount);
        set(11, finalAmount);
        set(12, flagActive);
        set(13, crudType);
        set(14, address);
    }
}
