/*
 * This file is generated by jOOQ.
*/
package com.vince.boot.demo.webapp.jooq.tables.records;


import com.vince.boot.demo.webapp.jooq.tables.DRelClientBlobH;

import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DRelClientBlobHRecord extends TableRecordImpl<DRelClientBlobHRecord> implements Record9<Long, Long, Timestamp, Timestamp, String, String, Long, Date, String> {

    private static final long serialVersionUID = 920368074;

    /**
     * Setter for <code>demo.d_rel_client_blob_h.fk_id_client</code>.
     */
    public void setFkIdClient(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>demo.d_rel_client_blob_h.fk_id_client</code>.
     */
    public Long getFkIdClient() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>demo.d_rel_client_blob_h.fk_id_blob</code>.
     */
    public void setFkIdBlob(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>demo.d_rel_client_blob_h.fk_id_blob</code>.
     */
    public Long getFkIdBlob() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>demo.d_rel_client_blob_h.time_insert</code>.
     */
    public void setTimeInsert(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>demo.d_rel_client_blob_h.time_insert</code>.
     */
    public Timestamp getTimeInsert() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>demo.d_rel_client_blob_h.time_update</code>.
     */
    public void setTimeUpdate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>demo.d_rel_client_blob_h.time_update</code>.
     */
    public Timestamp getTimeUpdate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>demo.d_rel_client_blob_h.user_insert</code>.
     */
    public void setUserInsert(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>demo.d_rel_client_blob_h.user_insert</code>.
     */
    public String getUserInsert() {
        return (String) get(4);
    }

    /**
     * Setter for <code>demo.d_rel_client_blob_h.user_update</code>.
     */
    public void setUserUpdate(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>demo.d_rel_client_blob_h.user_update</code>.
     */
    public String getUserUpdate() {
        return (String) get(5);
    }

    /**
     * Setter for <code>demo.d_rel_client_blob_h.id</code>.
     */
    public void setId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>demo.d_rel_client_blob_h.id</code>.
     */
    public Long getId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>demo.d_rel_client_blob_h.year_refer</code>.
     */
    public void setYearRefer(Date value) {
        set(7, value);
    }

    /**
     * Getter for <code>demo.d_rel_client_blob_h.year_refer</code>.
     */
    public Date getYearRefer() {
        return (Date) get(7);
    }

    /**
     * Setter for <code>demo.d_rel_client_blob_h.crud_type</code>.
     */
    public void setCrudType(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>demo.d_rel_client_blob_h.crud_type</code>.
     */
    public String getCrudType() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, Long, Timestamp, Timestamp, String, String, Long, Date, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, Long, Timestamp, Timestamp, String, String, Long, Date, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return DRelClientBlobH.D_REL_CLIENT_BLOB_H.FK_ID_CLIENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return DRelClientBlobH.D_REL_CLIENT_BLOB_H.FK_ID_BLOB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return DRelClientBlobH.D_REL_CLIENT_BLOB_H.TIME_INSERT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return DRelClientBlobH.D_REL_CLIENT_BLOB_H.TIME_UPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return DRelClientBlobH.D_REL_CLIENT_BLOB_H.USER_INSERT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return DRelClientBlobH.D_REL_CLIENT_BLOB_H.USER_UPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return DRelClientBlobH.D_REL_CLIENT_BLOB_H.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field8() {
        return DRelClientBlobH.D_REL_CLIENT_BLOB_H.YEAR_REFER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return DRelClientBlobH.D_REL_CLIENT_BLOB_H.CRUD_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getFkIdClient();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getFkIdBlob();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getTimeInsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getTimeUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUserInsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getUserUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component8() {
        return getYearRefer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getCrudType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getFkIdClient();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getFkIdBlob();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getTimeInsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getTimeUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUserInsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUserUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value8() {
        return getYearRefer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getCrudType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRelClientBlobHRecord value1(Long value) {
        setFkIdClient(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRelClientBlobHRecord value2(Long value) {
        setFkIdBlob(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRelClientBlobHRecord value3(Timestamp value) {
        setTimeInsert(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRelClientBlobHRecord value4(Timestamp value) {
        setTimeUpdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRelClientBlobHRecord value5(String value) {
        setUserInsert(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRelClientBlobHRecord value6(String value) {
        setUserUpdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRelClientBlobHRecord value7(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRelClientBlobHRecord value8(Date value) {
        setYearRefer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRelClientBlobHRecord value9(String value) {
        setCrudType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRelClientBlobHRecord values(Long value1, Long value2, Timestamp value3, Timestamp value4, String value5, String value6, Long value7, Date value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DRelClientBlobHRecord
     */
    public DRelClientBlobHRecord() {
        super(DRelClientBlobH.D_REL_CLIENT_BLOB_H);
    }

    /**
     * Create a detached, initialised DRelClientBlobHRecord
     */
    public DRelClientBlobHRecord(Long fkIdClient, Long fkIdBlob, Timestamp timeInsert, Timestamp timeUpdate, String userInsert, String userUpdate, Long id, Date yearRefer, String crudType) {
        super(DRelClientBlobH.D_REL_CLIENT_BLOB_H);

        set(0, fkIdClient);
        set(1, fkIdBlob);
        set(2, timeInsert);
        set(3, timeUpdate);
        set(4, userInsert);
        set(5, userUpdate);
        set(6, id);
        set(7, yearRefer);
        set(8, crudType);
    }
}
