/*
 * This file is generated by jOOQ.
*/
package com.vince.boot.demo.webapp.jooq.tables.records;


import com.vince.boot.demo.webapp.jooq.tables.DRelUserBlobH;

import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DRelUserBlobHRecord extends TableRecordImpl<DRelUserBlobHRecord> implements Record9<Long, Long, Long, byte[], String, Timestamp, Timestamp, Date, String> {

    private static final long serialVersionUID = 2091057998;

    /**
     * Setter for <code>demo.d_rel_user_blob_h.fk_id_user</code>.
     */
    public void setFkIdUser(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>demo.d_rel_user_blob_h.fk_id_user</code>.
     */
    public Long getFkIdUser() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>demo.d_rel_user_blob_h.fk_id_blob</code>.
     */
    public void setFkIdBlob(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>demo.d_rel_user_blob_h.fk_id_blob</code>.
     */
    public Long getFkIdBlob() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>demo.d_rel_user_blob_h.id</code>.
     */
    public void setId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>demo.d_rel_user_blob_h.id</code>.
     */
    public Long getId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>demo.d_rel_user_blob_h.user_insert</code>.
     */
    public void setUserInsert(byte... value) {
        set(3, value);
    }

    /**
     * Getter for <code>demo.d_rel_user_blob_h.user_insert</code>.
     */
    public byte[] getUserInsert() {
        return (byte[]) get(3);
    }

    /**
     * Setter for <code>demo.d_rel_user_blob_h.user_update</code>.
     */
    public void setUserUpdate(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>demo.d_rel_user_blob_h.user_update</code>.
     */
    public String getUserUpdate() {
        return (String) get(4);
    }

    /**
     * Setter for <code>demo.d_rel_user_blob_h.time_update</code>.
     */
    public void setTimeUpdate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>demo.d_rel_user_blob_h.time_update</code>.
     */
    public Timestamp getTimeUpdate() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>demo.d_rel_user_blob_h.time_insert</code>.
     */
    public void setTimeInsert(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>demo.d_rel_user_blob_h.time_insert</code>.
     */
    public Timestamp getTimeInsert() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>demo.d_rel_user_blob_h.year_refer</code>.
     */
    public void setYearRefer(Date value) {
        set(7, value);
    }

    /**
     * Getter for <code>demo.d_rel_user_blob_h.year_refer</code>.
     */
    public Date getYearRefer() {
        return (Date) get(7);
    }

    /**
     * Setter for <code>demo.d_rel_user_blob_h.crud_type</code>.
     */
    public void setCrudType(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>demo.d_rel_user_blob_h.crud_type</code>.
     */
    public String getCrudType() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, Long, Long, byte[], String, Timestamp, Timestamp, Date, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, Long, Long, byte[], String, Timestamp, Timestamp, Date, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return DRelUserBlobH.D_REL_USER_BLOB_H.FK_ID_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return DRelUserBlobH.D_REL_USER_BLOB_H.FK_ID_BLOB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return DRelUserBlobH.D_REL_USER_BLOB_H.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field4() {
        return DRelUserBlobH.D_REL_USER_BLOB_H.USER_INSERT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return DRelUserBlobH.D_REL_USER_BLOB_H.USER_UPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return DRelUserBlobH.D_REL_USER_BLOB_H.TIME_UPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return DRelUserBlobH.D_REL_USER_BLOB_H.TIME_INSERT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field8() {
        return DRelUserBlobH.D_REL_USER_BLOB_H.YEAR_REFER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return DRelUserBlobH.D_REL_USER_BLOB_H.CRUD_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getFkIdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getFkIdBlob();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component4() {
        return getUserInsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUserUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getTimeUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getTimeInsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component8() {
        return getYearRefer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getCrudType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getFkIdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getFkIdBlob();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value4() {
        return getUserInsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUserUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getTimeUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getTimeInsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value8() {
        return getYearRefer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getCrudType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRelUserBlobHRecord value1(Long value) {
        setFkIdUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRelUserBlobHRecord value2(Long value) {
        setFkIdBlob(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRelUserBlobHRecord value3(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRelUserBlobHRecord value4(byte... value) {
        setUserInsert(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRelUserBlobHRecord value5(String value) {
        setUserUpdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRelUserBlobHRecord value6(Timestamp value) {
        setTimeUpdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRelUserBlobHRecord value7(Timestamp value) {
        setTimeInsert(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRelUserBlobHRecord value8(Date value) {
        setYearRefer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRelUserBlobHRecord value9(String value) {
        setCrudType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRelUserBlobHRecord values(Long value1, Long value2, Long value3, byte[] value4, String value5, Timestamp value6, Timestamp value7, Date value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DRelUserBlobHRecord
     */
    public DRelUserBlobHRecord() {
        super(DRelUserBlobH.D_REL_USER_BLOB_H);
    }

    /**
     * Create a detached, initialised DRelUserBlobHRecord
     */
    public DRelUserBlobHRecord(Long fkIdUser, Long fkIdBlob, Long id, byte[] userInsert, String userUpdate, Timestamp timeUpdate, Timestamp timeInsert, Date yearRefer, String crudType) {
        super(DRelUserBlobH.D_REL_USER_BLOB_H);

        set(0, fkIdUser);
        set(1, fkIdBlob);
        set(2, id);
        set(3, userInsert);
        set(4, userUpdate);
        set(5, timeUpdate);
        set(6, timeInsert);
        set(7, yearRefer);
        set(8, crudType);
    }
}
