/*
 * This file is generated by jOOQ.
*/
package com.vince.boot.demo.webapp.jooq.tables.records;


import com.vince.boot.demo.webapp.jooq.tables.DRelClientBlob;

import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DRelClientBlobRecord extends UpdatableRecordImpl<DRelClientBlobRecord> implements Record8<Long, Long, Timestamp, Timestamp, String, String, Long, Date> {

    private static final long serialVersionUID = 1505242936;

    /**
     * Setter for <code>demo.d_rel_client_blob.fk_id_client</code>.
     */
    public void setFkIdClient(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>demo.d_rel_client_blob.fk_id_client</code>.
     */
    public Long getFkIdClient() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>demo.d_rel_client_blob.fk_id_blob</code>.
     */
    public void setFkIdBlob(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>demo.d_rel_client_blob.fk_id_blob</code>.
     */
    public Long getFkIdBlob() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>demo.d_rel_client_blob.time_insert</code>.
     */
    public void setTimeInsert(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>demo.d_rel_client_blob.time_insert</code>.
     */
    public Timestamp getTimeInsert() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>demo.d_rel_client_blob.time_update</code>.
     */
    public void setTimeUpdate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>demo.d_rel_client_blob.time_update</code>.
     */
    public Timestamp getTimeUpdate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>demo.d_rel_client_blob.user_insert</code>.
     */
    public void setUserInsert(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>demo.d_rel_client_blob.user_insert</code>.
     */
    public String getUserInsert() {
        return (String) get(4);
    }

    /**
     * Setter for <code>demo.d_rel_client_blob.user_update</code>.
     */
    public void setUserUpdate(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>demo.d_rel_client_blob.user_update</code>.
     */
    public String getUserUpdate() {
        return (String) get(5);
    }

    /**
     * Setter for <code>demo.d_rel_client_blob.id</code>.
     */
    public void setId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>demo.d_rel_client_blob.id</code>.
     */
    public Long getId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>demo.d_rel_client_blob.year_refer</code>.
     */
    public void setYearRefer(Date value) {
        set(7, value);
    }

    /**
     * Getter for <code>demo.d_rel_client_blob.year_refer</code>.
     */
    public Date getYearRefer() {
        return (Date) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Long, Timestamp, Timestamp, String, String, Long, Date> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Long, Timestamp, Timestamp, String, String, Long, Date> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return DRelClientBlob.D_REL_CLIENT_BLOB.FK_ID_CLIENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return DRelClientBlob.D_REL_CLIENT_BLOB.FK_ID_BLOB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return DRelClientBlob.D_REL_CLIENT_BLOB.TIME_INSERT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return DRelClientBlob.D_REL_CLIENT_BLOB.TIME_UPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return DRelClientBlob.D_REL_CLIENT_BLOB.USER_INSERT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return DRelClientBlob.D_REL_CLIENT_BLOB.USER_UPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return DRelClientBlob.D_REL_CLIENT_BLOB.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field8() {
        return DRelClientBlob.D_REL_CLIENT_BLOB.YEAR_REFER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getFkIdClient();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getFkIdBlob();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getTimeInsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getTimeUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUserInsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getUserUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component8() {
        return getYearRefer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getFkIdClient();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getFkIdBlob();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getTimeInsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getTimeUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUserInsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUserUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value8() {
        return getYearRefer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRelClientBlobRecord value1(Long value) {
        setFkIdClient(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRelClientBlobRecord value2(Long value) {
        setFkIdBlob(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRelClientBlobRecord value3(Timestamp value) {
        setTimeInsert(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRelClientBlobRecord value4(Timestamp value) {
        setTimeUpdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRelClientBlobRecord value5(String value) {
        setUserInsert(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRelClientBlobRecord value6(String value) {
        setUserUpdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRelClientBlobRecord value7(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRelClientBlobRecord value8(Date value) {
        setYearRefer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRelClientBlobRecord values(Long value1, Long value2, Timestamp value3, Timestamp value4, String value5, String value6, Long value7, Date value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DRelClientBlobRecord
     */
    public DRelClientBlobRecord() {
        super(DRelClientBlob.D_REL_CLIENT_BLOB);
    }

    /**
     * Create a detached, initialised DRelClientBlobRecord
     */
    public DRelClientBlobRecord(Long fkIdClient, Long fkIdBlob, Timestamp timeInsert, Timestamp timeUpdate, String userInsert, String userUpdate, Long id, Date yearRefer) {
        super(DRelClientBlob.D_REL_CLIENT_BLOB);

        set(0, fkIdClient);
        set(1, fkIdBlob);
        set(2, timeInsert);
        set(3, timeUpdate);
        set(4, userInsert);
        set(5, userUpdate);
        set(6, id);
        set(7, yearRefer);
    }
}
