/*
 * This file is generated by jOOQ.
*/
package com.vince.boot.demo.webapp.jooq.tables.records;


import com.vince.boot.demo.webapp.jooq.tables.DRoleFunction;

import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DRoleFunctionRecord extends UpdatableRecordImpl<DRoleFunctionRecord> implements Record6<String, String, Timestamp, Timestamp, Long, Date> {

    private static final long serialVersionUID = -1353815660;

    /**
     * Setter for <code>demo.d_role_function.user_insert</code>.
     */
    public void setUserInsert(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>demo.d_role_function.user_insert</code>.
     */
    public String getUserInsert() {
        return (String) get(0);
    }

    /**
     * Setter for <code>demo.d_role_function.user_update</code>.
     */
    public void setUserUpdate(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>demo.d_role_function.user_update</code>.
     */
    public String getUserUpdate() {
        return (String) get(1);
    }

    /**
     * Setter for <code>demo.d_role_function.time_insert</code>.
     */
    public void setTimeInsert(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>demo.d_role_function.time_insert</code>.
     */
    public Timestamp getTimeInsert() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>demo.d_role_function.time_update</code>.
     */
    public void setTimeUpdate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>demo.d_role_function.time_update</code>.
     */
    public Timestamp getTimeUpdate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>demo.d_role_function.id</code>.
     */
    public void setId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>demo.d_role_function.id</code>.
     */
    public Long getId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>demo.d_role_function.year_refer</code>.
     */
    public void setYearRefer(Date value) {
        set(5, value);
    }

    /**
     * Getter for <code>demo.d_role_function.year_refer</code>.
     */
    public Date getYearRefer() {
        return (Date) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, Timestamp, Timestamp, Long, Date> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, Timestamp, Timestamp, Long, Date> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return DRoleFunction.D_ROLE_FUNCTION.USER_INSERT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DRoleFunction.D_ROLE_FUNCTION.USER_UPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return DRoleFunction.D_ROLE_FUNCTION.TIME_INSERT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return DRoleFunction.D_ROLE_FUNCTION.TIME_UPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return DRoleFunction.D_ROLE_FUNCTION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field6() {
        return DRoleFunction.D_ROLE_FUNCTION.YEAR_REFER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getUserInsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUserUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getTimeInsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getTimeUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component6() {
        return getYearRefer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getUserInsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUserUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getTimeInsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getTimeUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value6() {
        return getYearRefer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRoleFunctionRecord value1(String value) {
        setUserInsert(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRoleFunctionRecord value2(String value) {
        setUserUpdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRoleFunctionRecord value3(Timestamp value) {
        setTimeInsert(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRoleFunctionRecord value4(Timestamp value) {
        setTimeUpdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRoleFunctionRecord value5(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRoleFunctionRecord value6(Date value) {
        setYearRefer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRoleFunctionRecord values(String value1, String value2, Timestamp value3, Timestamp value4, Long value5, Date value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DRoleFunctionRecord
     */
    public DRoleFunctionRecord() {
        super(DRoleFunction.D_ROLE_FUNCTION);
    }

    /**
     * Create a detached, initialised DRoleFunctionRecord
     */
    public DRoleFunctionRecord(String userInsert, String userUpdate, Timestamp timeInsert, Timestamp timeUpdate, Long id, Date yearRefer) {
        super(DRoleFunction.D_ROLE_FUNCTION);

        set(0, userInsert);
        set(1, userUpdate);
        set(2, timeInsert);
        set(3, timeUpdate);
        set(4, id);
        set(5, yearRefer);
    }
}
