/*
 * This file is generated by jOOQ.
*/
package com.vince.boot.demo.webapp.jooq.tables.records;


import com.vince.boot.demo.webapp.jooq.tables.DSystemProps;

import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DSystemPropsRecord extends UpdatableRecordImpl<DSystemPropsRecord> implements Record8<String, String, Timestamp, Timestamp, Long, Date, String, String> {

    private static final long serialVersionUID = 919696030;

    /**
     * Setter for <code>demo.d_system_props.user_insert</code>.
     */
    public void setUserInsert(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>demo.d_system_props.user_insert</code>.
     */
    public String getUserInsert() {
        return (String) get(0);
    }

    /**
     * Setter for <code>demo.d_system_props.user_update</code>.
     */
    public void setUserUpdate(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>demo.d_system_props.user_update</code>.
     */
    public String getUserUpdate() {
        return (String) get(1);
    }

    /**
     * Setter for <code>demo.d_system_props.time_insert</code>.
     */
    public void setTimeInsert(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>demo.d_system_props.time_insert</code>.
     */
    public Timestamp getTimeInsert() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>demo.d_system_props.time_update</code>.
     */
    public void setTimeUpdate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>demo.d_system_props.time_update</code>.
     */
    public Timestamp getTimeUpdate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>demo.d_system_props.id</code>.
     */
    public void setId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>demo.d_system_props.id</code>.
     */
    public Long getId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>demo.d_system_props.year_refer</code>.
     */
    public void setYearRefer(Date value) {
        set(5, value);
    }

    /**
     * Getter for <code>demo.d_system_props.year_refer</code>.
     */
    public Date getYearRefer() {
        return (Date) get(5);
    }

    /**
     * Setter for <code>demo.d_system_props.key_prop</code>.
     */
    public void setKeyProp(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>demo.d_system_props.key_prop</code>.
     */
    public String getKeyProp() {
        return (String) get(6);
    }

    /**
     * Setter for <code>demo.d_system_props.value_prop</code>.
     */
    public void setValueProp(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>demo.d_system_props.value_prop</code>.
     */
    public String getValueProp() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, Timestamp, Timestamp, Long, Date, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, Timestamp, Timestamp, Long, Date, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return DSystemProps.D_SYSTEM_PROPS.USER_INSERT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DSystemProps.D_SYSTEM_PROPS.USER_UPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return DSystemProps.D_SYSTEM_PROPS.TIME_INSERT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return DSystemProps.D_SYSTEM_PROPS.TIME_UPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return DSystemProps.D_SYSTEM_PROPS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field6() {
        return DSystemProps.D_SYSTEM_PROPS.YEAR_REFER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return DSystemProps.D_SYSTEM_PROPS.KEY_PROP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return DSystemProps.D_SYSTEM_PROPS.VALUE_PROP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getUserInsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUserUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getTimeInsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getTimeUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component6() {
        return getYearRefer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getKeyProp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getValueProp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getUserInsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUserUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getTimeInsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getTimeUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value6() {
        return getYearRefer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getKeyProp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getValueProp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DSystemPropsRecord value1(String value) {
        setUserInsert(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DSystemPropsRecord value2(String value) {
        setUserUpdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DSystemPropsRecord value3(Timestamp value) {
        setTimeInsert(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DSystemPropsRecord value4(Timestamp value) {
        setTimeUpdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DSystemPropsRecord value5(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DSystemPropsRecord value6(Date value) {
        setYearRefer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DSystemPropsRecord value7(String value) {
        setKeyProp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DSystemPropsRecord value8(String value) {
        setValueProp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DSystemPropsRecord values(String value1, String value2, Timestamp value3, Timestamp value4, Long value5, Date value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DSystemPropsRecord
     */
    public DSystemPropsRecord() {
        super(DSystemProps.D_SYSTEM_PROPS);
    }

    /**
     * Create a detached, initialised DSystemPropsRecord
     */
    public DSystemPropsRecord(String userInsert, String userUpdate, Timestamp timeInsert, Timestamp timeUpdate, Long id, Date yearRefer, String keyProp, String valueProp) {
        super(DSystemProps.D_SYSTEM_PROPS);

        set(0, userInsert);
        set(1, userUpdate);
        set(2, timeInsert);
        set(3, timeUpdate);
        set(4, id);
        set(5, yearRefer);
        set(6, keyProp);
        set(7, valueProp);
    }
}
