package com.vince.boot.demo.webapp.entity;
// Generated 4-ott-2017 15.34.34 by Hibernate Tools 3.2.2.GA


import java.util.Arrays;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DBlobStoreHId generated by hbm2java
 */
@Embeddable
public class DBlobStoreHId  implements java.io.Serializable {


     private Integer userInsert;
     private Integer userUpdate;
     private Date timeInsert;
     private Date timeUpdate;
     private Long id;
     private String filename;
     private Character flagActive;
     private byte[] blobData;
     private Long fkIdType;
     private String description;
     private String contentType;
     private Date yearRefer;
     private char crudType;

    public DBlobStoreHId() {
    }

	
    public DBlobStoreHId(Date yearRefer, char crudType) {
        this.yearRefer = yearRefer;
        this.crudType = crudType;
    }
    public DBlobStoreHId(Integer userInsert, Integer userUpdate, Date timeInsert, Date timeUpdate, Long id, String filename, Character flagActive, byte[] blobData, Long fkIdType, String description, String contentType, Date yearRefer, char crudType) {
       this.userInsert = userInsert;
       this.userUpdate = userUpdate;
       this.timeInsert = timeInsert;
       this.timeUpdate = timeUpdate;
       this.id = id;
       this.filename = filename;
       this.flagActive = flagActive;
       this.blobData = blobData;
       this.fkIdType = fkIdType;
       this.description = description;
       this.contentType = contentType;
       this.yearRefer = yearRefer;
       this.crudType = crudType;
    }
   

    @Column(name="user_insert")
    public Integer getUserInsert() {
        return this.userInsert;
    }
    
    public void setUserInsert(Integer userInsert) {
        this.userInsert = userInsert;
    }

    @Column(name="user_update")
    public Integer getUserUpdate() {
        return this.userUpdate;
    }
    
    public void setUserUpdate(Integer userUpdate) {
        this.userUpdate = userUpdate;
    }

    @Column(name="time_insert", length=19)
    public Date getTimeInsert() {
        return this.timeInsert;
    }
    
    public void setTimeInsert(Date timeInsert) {
        this.timeInsert = timeInsert;
    }

    @Column(name="time_update", length=19)
    public Date getTimeUpdate() {
        return this.timeUpdate;
    }
    
    public void setTimeUpdate(Date timeUpdate) {
        this.timeUpdate = timeUpdate;
    }

    @Column(name="id")
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    @Column(name="filename", length=200)
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }

    @Column(name="flag_active", length=1)
    public Character getFlagActive() {
        return this.flagActive;
    }
    
    public void setFlagActive(Character flagActive) {
        this.flagActive = flagActive;
    }

    @Column(name="blob_data")
    public byte[] getBlobData() {
        return this.blobData;
    }
    
    public void setBlobData(byte[] blobData) {
        this.blobData = blobData;
    }

    @Column(name="fk_id_type")
    public Long getFkIdType() {
        return this.fkIdType;
    }
    
    public void setFkIdType(Long fkIdType) {
        this.fkIdType = fkIdType;
    }

    @Column(name="description", length=200)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name="content_type", length=100)
    public String getContentType() {
        return this.contentType;
    }
    
    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    @Column(name="year_refer", nullable=false, length=10)
    public Date getYearRefer() {
        return this.yearRefer;
    }
    
    public void setYearRefer(Date yearRefer) {
        this.yearRefer = yearRefer;
    }

    @Column(name="crud_type", nullable=false, length=1)
    public char getCrudType() {
        return this.crudType;
    }
    
    public void setCrudType(char crudType) {
        this.crudType = crudType;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DBlobStoreHId) ) return false;
		 DBlobStoreHId castOther = ( DBlobStoreHId ) other; 
         
		 return ( (this.getUserInsert()==castOther.getUserInsert()) || ( this.getUserInsert()!=null && castOther.getUserInsert()!=null && this.getUserInsert().equals(castOther.getUserInsert()) ) )
 && ( (this.getUserUpdate()==castOther.getUserUpdate()) || ( this.getUserUpdate()!=null && castOther.getUserUpdate()!=null && this.getUserUpdate().equals(castOther.getUserUpdate()) ) )
 && ( (this.getTimeInsert()==castOther.getTimeInsert()) || ( this.getTimeInsert()!=null && castOther.getTimeInsert()!=null && this.getTimeInsert().equals(castOther.getTimeInsert()) ) )
 && ( (this.getTimeUpdate()==castOther.getTimeUpdate()) || ( this.getTimeUpdate()!=null && castOther.getTimeUpdate()!=null && this.getTimeUpdate().equals(castOther.getTimeUpdate()) ) )
 && ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getFilename()==castOther.getFilename()) || ( this.getFilename()!=null && castOther.getFilename()!=null && this.getFilename().equals(castOther.getFilename()) ) )
 && ( (this.getFlagActive()==castOther.getFlagActive()) || ( this.getFlagActive()!=null && castOther.getFlagActive()!=null && this.getFlagActive().equals(castOther.getFlagActive()) ) )
 && ( (this.getBlobData()==castOther.getBlobData()) || ( this.getBlobData()!=null && castOther.getBlobData()!=null && Arrays.equals(this.getBlobData(), castOther.getBlobData()) ) )
 && ( (this.getFkIdType()==castOther.getFkIdType()) || ( this.getFkIdType()!=null && castOther.getFkIdType()!=null && this.getFkIdType().equals(castOther.getFkIdType()) ) )
 && ( (this.getDescription()==castOther.getDescription()) || ( this.getDescription()!=null && castOther.getDescription()!=null && this.getDescription().equals(castOther.getDescription()) ) )
 && ( (this.getContentType()==castOther.getContentType()) || ( this.getContentType()!=null && castOther.getContentType()!=null && this.getContentType().equals(castOther.getContentType()) ) )
 && ( (this.getYearRefer()==castOther.getYearRefer()) || ( this.getYearRefer()!=null && castOther.getYearRefer()!=null && this.getYearRefer().equals(castOther.getYearRefer()) ) )
 && (this.getCrudType()==castOther.getCrudType());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserInsert() == null ? 0 : this.getUserInsert().hashCode() );
         result = 37 * result + ( getUserUpdate() == null ? 0 : this.getUserUpdate().hashCode() );
         result = 37 * result + ( getTimeInsert() == null ? 0 : this.getTimeInsert().hashCode() );
         result = 37 * result + ( getTimeUpdate() == null ? 0 : this.getTimeUpdate().hashCode() );
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getFilename() == null ? 0 : this.getFilename().hashCode() );
         result = 37 * result + ( getFlagActive() == null ? 0 : this.getFlagActive().hashCode() );
         result = 37 * result + ( getBlobData() == null ? 0 : Arrays.hashCode(this.getBlobData()) );
         result = 37 * result + ( getFkIdType() == null ? 0 : this.getFkIdType().hashCode() );
         result = 37 * result + ( getDescription() == null ? 0 : this.getDescription().hashCode() );
         result = 37 * result + ( getContentType() == null ? 0 : this.getContentType().hashCode() );
         result = 37 * result + ( getYearRefer() == null ? 0 : this.getYearRefer().hashCode() );
         result = 37 * result + this.getCrudType();
         return result;
   }   


}


