package com.vince.boot.demo.webapp.entity;
// Generated 4-ott-2017 15.34.34 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DClientApp generated by hbm2java
 */
@Entity
@Table(name="d_client_app"
    ,catalog="demo"
)
public class DClientApp  implements java.io.Serializable {


     private long id;
     private String userInsert;
     private String userUpdate;
     private Date timeInsert;
     private Date timeUpdate;
     private String name;
     private String piva;
     private String address;
     private String zipcode;
     private String notes;
     private String phone;
     private String email;
     private Date yearRefer;
     private Set<DRelClientBlob> DRelClientBlobs = new HashSet<DRelClientBlob>(0);
     private Set<DOrderJob> DOrderJobs = new HashSet<DOrderJob>(0);

    public DClientApp() {
    }

	
    public DClientApp(long id, String userInsert, Date timeInsert, String name, String piva, String address, String zipcode, String notes, Date yearRefer) {
        this.id = id;
        this.userInsert = userInsert;
        this.timeInsert = timeInsert;
        this.name = name;
        this.piva = piva;
        this.address = address;
        this.zipcode = zipcode;
        this.notes = notes;
        this.yearRefer = yearRefer;
    }
    public DClientApp(long id, String userInsert, String userUpdate, Date timeInsert, Date timeUpdate, String name, String piva, String address, String zipcode, String notes, String phone, String email, Date yearRefer, Set<DRelClientBlob> DRelClientBlobs, Set<DOrderJob> DOrderJobs) {
       this.id = id;
       this.userInsert = userInsert;
       this.userUpdate = userUpdate;
       this.timeInsert = timeInsert;
       this.timeUpdate = timeUpdate;
       this.name = name;
       this.piva = piva;
       this.address = address;
       this.zipcode = zipcode;
       this.notes = notes;
       this.phone = phone;
       this.email = email;
       this.yearRefer = yearRefer;
       this.DRelClientBlobs = DRelClientBlobs;
       this.DOrderJobs = DOrderJobs;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="user_insert", nullable=false, length=100)
    public String getUserInsert() {
        return this.userInsert;
    }
    
    public void setUserInsert(String userInsert) {
        this.userInsert = userInsert;
    }
    
    @Column(name="user_update", length=100)
    public String getUserUpdate() {
        return this.userUpdate;
    }
    
    public void setUserUpdate(String userUpdate) {
        this.userUpdate = userUpdate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="time_insert", nullable=false, length=19)
    public Date getTimeInsert() {
        return this.timeInsert;
    }
    
    public void setTimeInsert(Date timeInsert) {
        this.timeInsert = timeInsert;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="time_update", length=19)
    public Date getTimeUpdate() {
        return this.timeUpdate;
    }
    
    public void setTimeUpdate(Date timeUpdate) {
        this.timeUpdate = timeUpdate;
    }
    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="piva", nullable=false, length=16)
    public String getPiva() {
        return this.piva;
    }
    
    public void setPiva(String piva) {
        this.piva = piva;
    }
    
    @Column(name="address", nullable=false, length=2000)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    @Column(name="zipcode", nullable=false, length=5)
    public String getZipcode() {
        return this.zipcode;
    }
    
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }
    
    @Column(name="notes", nullable=false, length=2000)
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    
    @Column(name="phone", length=100)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="year_refer", nullable=false, length=10)
    public Date getYearRefer() {
        return this.yearRefer;
    }
    
    public void setYearRefer(Date yearRefer) {
        this.yearRefer = yearRefer;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="DClientApp")
    public Set<DRelClientBlob> getDRelClientBlobs() {
        return this.DRelClientBlobs;
    }
    
    public void setDRelClientBlobs(Set<DRelClientBlob> DRelClientBlobs) {
        this.DRelClientBlobs = DRelClientBlobs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="DClientApp")
    public Set<DOrderJob> getDOrderJobs() {
        return this.DOrderJobs;
    }
    
    public void setDOrderJobs(Set<DOrderJob> DOrderJobs) {
        this.DOrderJobs = DOrderJobs;
    }




}


