package com.vince.boot.demo.webapp.entity;
// Generated 4-ott-2017 15.34.34 by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DClientH generated by hbm2java
 */
@Entity
@Table(name="d_client_h"
    ,catalog="demo"
)
public class DClientH  implements java.io.Serializable {


     private DClientHId id;

    public DClientH() {
    }

    public DClientH(DClientHId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="userInsert", column=@Column(name="user_insert") ), 
        @AttributeOverride(name="userUpdate", column=@Column(name="user_update") ), 
        @AttributeOverride(name="timeInsert", column=@Column(name="time_insert", length=19) ), 
        @AttributeOverride(name="timeUpdate", column=@Column(name="time_update", length=19) ), 
        @AttributeOverride(name="id", column=@Column(name="id") ), 
        @AttributeOverride(name="name", column=@Column(name="name", length=100) ), 
        @AttributeOverride(name="piva", column=@Column(name="piva", length=16) ), 
        @AttributeOverride(name="address", column=@Column(name="address", length=200) ), 
        @AttributeOverride(name="zipcode", column=@Column(name="zipcode", length=5) ), 
        @AttributeOverride(name="notes", column=@Column(name="notes", length=2000) ), 
        @AttributeOverride(name="phone", column=@Column(name="phone", length=100) ), 
        @AttributeOverride(name="email", column=@Column(name="email", length=100) ), 
        @AttributeOverride(name="yearRefer", column=@Column(name="year_refer", nullable=false, length=10) ), 
        @AttributeOverride(name="crudType", column=@Column(name="crud_type", nullable=false, length=1) ) } )
    public DClientHId getId() {
        return this.id;
    }
    
    public void setId(DClientHId id) {
        this.id = id;
    }




}


