package com.vince.boot.demo.webapp.entity;
// Generated 4-ott-2017 15.34.34 by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DGeoLocalH generated by hbm2java
 */
@Entity
@Table(name="d_geo_local_h"
    ,catalog="demo"
)
public class DGeoLocalH  implements java.io.Serializable {


     private DGeoLocalHId id;

    public DGeoLocalH() {
    }

    public DGeoLocalH(DGeoLocalHId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="userInsert", column=@Column(name="user_insert") ), 
        @AttributeOverride(name="userUpdate", column=@Column(name="user_update") ), 
        @AttributeOverride(name="timeInsert", column=@Column(name="time_insert", length=19) ), 
        @AttributeOverride(name="timeUpdate", column=@Column(name="time_update", length=19) ), 
        @AttributeOverride(name="id", column=@Column(name="id") ), 
        @AttributeOverride(name="yearRefer", column=@Column(name="year_refer", nullable=false, length=10) ), 
        @AttributeOverride(name="crudType", column=@Column(name="crud_type", nullable=false, length=1) ) } )
    public DGeoLocalHId getId() {
        return this.id;
    }
    
    public void setId(DGeoLocalHId id) {
        this.id = id;
    }




}


