package com.vince.boot.demo.webapp.entity;
// Generated 4-ott-2017 15.34.34 by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DOrderJobH generated by hbm2java
 */
@Entity
@Table(name="d_order_job_h"
    ,catalog="demo"
)
public class DOrderJobH  implements java.io.Serializable {


     private DOrderJobHId id;

    public DOrderJobH() {
    }

    public DOrderJobH(DOrderJobHId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="userInsert", column=@Column(name="user_insert", length=100) ), 
        @AttributeOverride(name="userUpdate", column=@Column(name="user_update", length=100) ), 
        @AttributeOverride(name="timeInsert", column=@Column(name="time_insert", length=19) ), 
        @AttributeOverride(name="timeUpdate", column=@Column(name="time_update", length=19) ), 
        @AttributeOverride(name="id", column=@Column(name="id") ), 
        @AttributeOverride(name="fkIdClient", column=@Column(name="fk_id_client") ), 
        @AttributeOverride(name="notes", column=@Column(name="notes", length=2000) ), 
        @AttributeOverride(name="codeOrder", column=@Column(name="code_order", length=20) ), 
        @AttributeOverride(name="dataScadenza", column=@Column(name="data_scadenza", length=19) ), 
        @AttributeOverride(name="yearRefer", column=@Column(name="year_refer", nullable=false, length=10) ), 
        @AttributeOverride(name="preAmount", column=@Column(name="pre_amount", precision=10) ), 
        @AttributeOverride(name="finalAmount", column=@Column(name="final_amount", precision=10) ), 
        @AttributeOverride(name="flagActive", column=@Column(name="flag_active", length=1) ), 
        @AttributeOverride(name="crudType", column=@Column(name="crud_type", nullable=false, length=1) ), 
        @AttributeOverride(name="address", column=@Column(name="address") ) } )
    public DOrderJobHId getId() {
        return this.id;
    }
    
    public void setId(DOrderJobHId id) {
        this.id = id;
    }




}


