package com.vince.boot.demo.webapp.entity;
// Generated 4-ott-2017 15.34.34 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DRelUserBlob generated by hbm2java
 */
@Entity
@Table(name="d_rel_user_blob"
    ,catalog="demo"
)
public class DRelUserBlob  implements java.io.Serializable {


     private Long id;
     private DBlobStore DBlobStore;
     private DUserApp DUserApp;
     private String userInsert;
     private String userUpdate;
     private Date timeUpdate;
     private Date timeInsert;
     private Date yearRefer;

    public DRelUserBlob() {
    }

	
    public DRelUserBlob(DBlobStore DBlobStore, DUserApp DUserApp, String userInsert, Date timeInsert, Date yearRefer) {
        this.DBlobStore = DBlobStore;
        this.DUserApp = DUserApp;
        this.userInsert = userInsert;
        this.timeInsert = timeInsert;
        this.yearRefer = yearRefer;
    }
    public DRelUserBlob(DBlobStore DBlobStore, DUserApp DUserApp, String userInsert, String userUpdate, Date timeUpdate, Date timeInsert, Date yearRefer) {
       this.DBlobStore = DBlobStore;
       this.DUserApp = DUserApp;
       this.userInsert = userInsert;
       this.userUpdate = userUpdate;
       this.timeUpdate = timeUpdate;
       this.timeInsert = timeInsert;
       this.yearRefer = yearRefer;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_id_blob", nullable=false)
    public DBlobStore getDBlobStore() {
        return this.DBlobStore;
    }
    
    public void setDBlobStore(DBlobStore DBlobStore) {
        this.DBlobStore = DBlobStore;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_id_user", nullable=false)
    public DUserApp getDUserApp() {
        return this.DUserApp;
    }
    
    public void setDUserApp(DUserApp DUserApp) {
        this.DUserApp = DUserApp;
    }
    
    @Column(name="user_insert", nullable=false, length=100)
    public String getUserInsert() {
        return this.userInsert;
    }
    
    public void setUserInsert(String userInsert) {
        this.userInsert = userInsert;
    }
    
    @Column(name="user_update", length=100)
    public String getUserUpdate() {
        return this.userUpdate;
    }
    
    public void setUserUpdate(String userUpdate) {
        this.userUpdate = userUpdate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="time_update", length=19)
    public Date getTimeUpdate() {
        return this.timeUpdate;
    }
    
    public void setTimeUpdate(Date timeUpdate) {
        this.timeUpdate = timeUpdate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="time_insert", nullable=false, length=19)
    public Date getTimeInsert() {
        return this.timeInsert;
    }
    
    public void setTimeInsert(Date timeInsert) {
        this.timeInsert = timeInsert;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="year_refer", nullable=false, length=10)
    public Date getYearRefer() {
        return this.yearRefer;
    }
    
    public void setYearRefer(Date yearRefer) {
        this.yearRefer = yearRefer;
    }




}


