package com.vince.boot.demo.webapp.entity;
// Generated 4-ott-2017 15.34.34 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DRoleFunction generated by hbm2java
 */
@Entity
@Table(name="d_role_function"
    ,catalog="demo"
)
public class DRoleFunction  implements java.io.Serializable {


     private long id;
     private DRoleUser DRoleUser;
     private String userInsert;
     private String userUpdate;
     private Date timeInsert;
     private Date timeUpdate;
     private Date yearRefer;

    public DRoleFunction() {
    }

	
    public DRoleFunction(long id, DRoleUser DRoleUser, String userInsert, Date timeInsert, Date yearRefer) {
        this.id = id;
        this.DRoleUser = DRoleUser;
        this.userInsert = userInsert;
        this.timeInsert = timeInsert;
        this.yearRefer = yearRefer;
    }
    public DRoleFunction(long id, DRoleUser DRoleUser, String userInsert, String userUpdate, Date timeInsert, Date timeUpdate, Date yearRefer) {
       this.id = id;
       this.DRoleUser = DRoleUser;
       this.userInsert = userInsert;
       this.userUpdate = userUpdate;
       this.timeInsert = timeInsert;
       this.timeUpdate = timeUpdate;
       this.yearRefer = yearRefer;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id", unique=true, nullable=false, insertable=false, updatable=false)
    public DRoleUser getDRoleUser() {
        return this.DRoleUser;
    }
    
    public void setDRoleUser(DRoleUser DRoleUser) {
        this.DRoleUser = DRoleUser;
    }
    
    @Column(name="user_insert", nullable=false, length=100)
    public String getUserInsert() {
        return this.userInsert;
    }
    
    public void setUserInsert(String userInsert) {
        this.userInsert = userInsert;
    }
    
    @Column(name="user_update", length=100)
    public String getUserUpdate() {
        return this.userUpdate;
    }
    
    public void setUserUpdate(String userUpdate) {
        this.userUpdate = userUpdate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="time_insert", nullable=false, length=19)
    public Date getTimeInsert() {
        return this.timeInsert;
    }
    
    public void setTimeInsert(Date timeInsert) {
        this.timeInsert = timeInsert;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="time_update", length=19)
    public Date getTimeUpdate() {
        return this.timeUpdate;
    }
    
    public void setTimeUpdate(Date timeUpdate) {
        this.timeUpdate = timeUpdate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="year_refer", nullable=false, length=10)
    public Date getYearRefer() {
        return this.yearRefer;
    }
    
    public void setYearRefer(Date yearRefer) {
        this.yearRefer = yearRefer;
    }




}


