package com.vince.boot.demo.webapp.entity;
// Generated 4-ott-2017 15.34.34 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * DRoleUser generated by hbm2java
 */
@Entity
@Table(name="d_role_user"
    ,catalog="demo"
    , uniqueConstraints = @UniqueConstraint(columnNames="role_code") 
)
public class DRoleUser  implements java.io.Serializable {


     private long id;
     private String userInsert;
     private String userUpdate;
     private Date timeInsert;
     private Date timeUpdate;
     private String roleCode;
     private String roleDescription;
     private Date yearRefer;
     private Set<DUserApp> DUserApps = new HashSet<DUserApp>(0);
     private Set<DRoleFunction> DRoleFunctions = new HashSet<DRoleFunction>(0);

    public DRoleUser() {
    }

	
    public DRoleUser(long id, String userInsert, Date timeInsert, String roleCode, String roleDescription, Date yearRefer) {
        this.id = id;
        this.userInsert = userInsert;
        this.timeInsert = timeInsert;
        this.roleCode = roleCode;
        this.roleDescription = roleDescription;
        this.yearRefer = yearRefer;
    }
    public DRoleUser(long id, String userInsert, String userUpdate, Date timeInsert, Date timeUpdate, String roleCode, String roleDescription, Date yearRefer, Set<DUserApp> DUserApps, Set<DRoleFunction> DRoleFunctions) {
       this.id = id;
       this.userInsert = userInsert;
       this.userUpdate = userUpdate;
       this.timeInsert = timeInsert;
       this.timeUpdate = timeUpdate;
       this.roleCode = roleCode;
       this.roleDescription = roleDescription;
       this.yearRefer = yearRefer;
       this.DUserApps = DUserApps;
       this.DRoleFunctions = DRoleFunctions;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="user_insert", nullable=false, length=100)
    public String getUserInsert() {
        return this.userInsert;
    }
    
    public void setUserInsert(String userInsert) {
        this.userInsert = userInsert;
    }
    
    @Column(name="user_update", length=100)
    public String getUserUpdate() {
        return this.userUpdate;
    }
    
    public void setUserUpdate(String userUpdate) {
        this.userUpdate = userUpdate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="time_insert", nullable=false, length=19)
    public Date getTimeInsert() {
        return this.timeInsert;
    }
    
    public void setTimeInsert(Date timeInsert) {
        this.timeInsert = timeInsert;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="time_update", length=19)
    public Date getTimeUpdate() {
        return this.timeUpdate;
    }
    
    public void setTimeUpdate(Date timeUpdate) {
        this.timeUpdate = timeUpdate;
    }
    
    @Column(name="role_code", unique=true, nullable=false, length=20)
    public String getRoleCode() {
        return this.roleCode;
    }
    
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }
    
    @Column(name="role_description", nullable=false, length=100)
    public String getRoleDescription() {
        return this.roleDescription;
    }
    
    public void setRoleDescription(String roleDescription) {
        this.roleDescription = roleDescription;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="year_refer", nullable=false, length=10)
    public Date getYearRefer() {
        return this.yearRefer;
    }
    
    public void setYearRefer(Date yearRefer) {
        this.yearRefer = yearRefer;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="DRoleUser")
    public Set<DUserApp> getDUserApps() {
        return this.DUserApps;
    }
    
    public void setDUserApps(Set<DUserApp> DUserApps) {
        this.DUserApps = DUserApps;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="DRoleUser")
    public Set<DRoleFunction> getDRoleFunctions() {
        return this.DRoleFunctions;
    }
    
    public void setDRoleFunctions(Set<DRoleFunction> DRoleFunctions) {
        this.DRoleFunctions = DRoleFunctions;
    }




}


