package com.vince.boot.demo.webapp.entity;
// Generated 4-ott-2017 15.34.34 by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DTypeDocumentH generated by hbm2java
 */
@Entity
@Table(name="d_type_document_h"
    ,catalog="demo"
)
public class DTypeDocumentH  implements java.io.Serializable {


     private DTypeDocumentHId id;

    public DTypeDocumentH() {
    }

    public DTypeDocumentH(DTypeDocumentHId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="userInsert", column=@Column(name="user_insert") ), 
        @AttributeOverride(name="userUpdate", column=@Column(name="user_update") ), 
        @AttributeOverride(name="timeInsert", column=@Column(name="time_insert", length=19) ), 
        @AttributeOverride(name="timeUpdate", column=@Column(name="time_update", length=19) ), 
        @AttributeOverride(name="id", column=@Column(name="id") ), 
        @AttributeOverride(name="typeCode", column=@Column(name="type_code", length=20) ), 
        @AttributeOverride(name="typeDescription", column=@Column(name="type_description", length=100) ), 
        @AttributeOverride(name="yearRefer", column=@Column(name="year_refer", nullable=false, length=10) ), 
        @AttributeOverride(name="crudType", column=@Column(name="crud_type", nullable=false, length=1) ) } )
    public DTypeDocumentHId getId() {
        return this.id;
    }
    
    public void setId(DTypeDocumentHId id) {
        this.id = id;
    }




}


