package com.vince.boot.demo.webapp.entity;
// Generated 4-ott-2017 15.34.34 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * DUserApp generated by hbm2java
 */
@Entity
@Table(name="d_user_app"
    ,catalog="demo"
    , uniqueConstraints = @UniqueConstraint(columnNames="username") 
)
public class DUserApp  implements java.io.Serializable {


     private Long id;
     private DRoleUser DRoleUser;
     private String username;
     private String userInsert;
     private String userUpdate;
     private Date timeInsert;
     private Date timeUpdate;
     private String password;
     private String firstName;
     private String lastName;
     private String email;
     private Long fkIdBlobStore;
     private Date yearRefer;
     private String address;
     private Set<DRelUserBlob> DRelUserBlobs = new HashSet<DRelUserBlob>(0);

    public DUserApp() {
    }

	
    public DUserApp(DRoleUser DRoleUser, String username, String userInsert, Date timeInsert, String password, String firstName, String lastName, Date yearRefer) {
        this.DRoleUser = DRoleUser;
        this.username = username;
        this.userInsert = userInsert;
        this.timeInsert = timeInsert;
        this.password = password;
        this.firstName = firstName;
        this.lastName = lastName;
        this.yearRefer = yearRefer;
    }
    public DUserApp(DRoleUser DRoleUser, String username, String userInsert, String userUpdate, Date timeInsert, Date timeUpdate, String password, String firstName, String lastName, String email, Long fkIdBlobStore, Date yearRefer, String address, Set<DRelUserBlob> DRelUserBlobs) {
       this.DRoleUser = DRoleUser;
       this.username = username;
       this.userInsert = userInsert;
       this.userUpdate = userUpdate;
       this.timeInsert = timeInsert;
       this.timeUpdate = timeUpdate;
       this.password = password;
       this.firstName = firstName;
       this.lastName = lastName;
       this.email = email;
       this.fkIdBlobStore = fkIdBlobStore;
       this.yearRefer = yearRefer;
       this.address = address;
       this.DRelUserBlobs = DRelUserBlobs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_id_role_user", nullable=false)
    public DRoleUser getDRoleUser() {
        return this.DRoleUser;
    }
    
    public void setDRoleUser(DRoleUser DRoleUser) {
        this.DRoleUser = DRoleUser;
    }
    
    @Column(name="username", unique=true, nullable=false, length=100)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    @Column(name="user_insert", nullable=false, length=100)
    public String getUserInsert() {
        return this.userInsert;
    }
    
    public void setUserInsert(String userInsert) {
        this.userInsert = userInsert;
    }
    
    @Column(name="user_update", length=100)
    public String getUserUpdate() {
        return this.userUpdate;
    }
    
    public void setUserUpdate(String userUpdate) {
        this.userUpdate = userUpdate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="time_insert", nullable=false, length=19)
    public Date getTimeInsert() {
        return this.timeInsert;
    }
    
    public void setTimeInsert(Date timeInsert) {
        this.timeInsert = timeInsert;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="time_update", length=19)
    public Date getTimeUpdate() {
        return this.timeUpdate;
    }
    
    public void setTimeUpdate(Date timeUpdate) {
        this.timeUpdate = timeUpdate;
    }
    
    @Column(name="password", nullable=false, length=20)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="first_name", nullable=false, length=50)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    
    @Column(name="last_name", nullable=false, length=50)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="fk_id_blob_store")
    public Long getFkIdBlobStore() {
        return this.fkIdBlobStore;
    }
    
    public void setFkIdBlobStore(Long fkIdBlobStore) {
        this.fkIdBlobStore = fkIdBlobStore;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="year_refer", nullable=false, length=10)
    public Date getYearRefer() {
        return this.yearRefer;
    }
    
    public void setYearRefer(Date yearRefer) {
        this.yearRefer = yearRefer;
    }
    
    @Column(name="address", length=2000)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="DUserApp")
    public Set<DRelUserBlob> getDRelUserBlobs() {
        return this.DRelUserBlobs;
    }
    
    public void setDRelUserBlobs(Set<DRelUserBlob> DRelUserBlobs) {
        this.DRelUserBlobs = DRelUserBlobs;
    }




}


