package com.vince.boot.demo.webapp.be.entity;
// Generated 4-ott-2017 15.34.34 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DBlobStore generated by hbm2java
 */
@Entity
@Table(name = "d_blob_store")
public class BlobStore extends BaseEntity {

	private static final long serialVersionUID = 1L;
	private TypeDocument typeDocument;

	private String filename;
	private char flagActive;
	private byte[] blobData;
	private String description;
	private String contentType;

	private Set<RelOrderBlob> relOrderBlobs = new HashSet<RelOrderBlob>(0);
	private Set<RelUserBlob> relUserBlobs = new HashSet<RelUserBlob>(0);
	private Set<RelClientBlob> relClientBlobs = new HashSet<RelClientBlob>(0);

	public BlobStore() {
	}


	public BlobStore(Long id) {
		super.id = id;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_id_type", nullable = false)
	public TypeDocument getTypeDocument() {
		return this.typeDocument;
	}

	public void setTypeDocument(TypeDocument typeDocument) {
		this.typeDocument = typeDocument;
	}

	@Column(name = "filename", nullable = false, length = 200)
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Column(name = "flag_active", nullable = false, length = 1)
	public char getFlagActive() {
		return this.flagActive;
	}

	public void setFlagActive(char flagActive) {
		this.flagActive = flagActive;
	}

	@Column(name = "blob_data", nullable = false)
	public byte[] getBlobData() {
		return this.blobData;
	}

	public void setBlobData(byte[] blobData) {
		this.blobData = blobData;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "content_type", nullable = false, length = 100)
	public String getContentType() {
		return this.contentType;
	}

	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "blobStore")
	public Set<RelOrderBlob> getRelOrderBlobs() {
		return this.relOrderBlobs;
	}

	public void setRelOrderBlobs(Set<RelOrderBlob> RelOrderBlobs) {
		this.relOrderBlobs = RelOrderBlobs;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "blobStore")
	public Set<RelUserBlob> getRelUserBlobs() {
		return this.relUserBlobs;
	}

	public void setRelUserBlobs(Set<RelUserBlob> RelUserBlobs) {
		this.relUserBlobs = RelUserBlobs;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "blobStore")
	public Set<RelClientBlob> getRelClientBlobs() {
		return this.relClientBlobs;
	}

	public void setRelClientBlobs(Set<RelClientBlob> RelClientBlobs) {
		this.relClientBlobs = RelClientBlobs;
	}

}
