package com.vince.boot.demo.webapp.be.entity;
// Generated 4-ott-2017 15.34.34 by Hibernate Tools 3.2.2.GA

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DRelOrderBlob generated by hbm2java
 */
@Entity
@Table(name = "d_rel_order_blob")
public class DRelOrderBlob extends BaseEntity {

	private static final long serialVersionUID = 1L;
	private DOrderJob DOrderJob;
	private DBlobStore DBlobStore;

	public DRelOrderBlob() {
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_id_order", nullable = false)
	public DOrderJob getDOrderJob() {
		return this.DOrderJob;
	}

	public void setDOrderJob(DOrderJob DOrderJob) {
		this.DOrderJob = DOrderJob;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_id_blob", nullable = false)
	public DBlobStore getDBlobStore() {
		return this.DBlobStore;
	}

	public void setDBlobStore(DBlobStore DBlobStore) {
		this.DBlobStore = DBlobStore;
	}

}
