package com.vince.boot.demo.webapp.be.entity;
// Generated 4-ott-2017 15.34.34 by Hibernate Tools 3.2.2.GA

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DRelUserBlob generated by hbm2java
 */
@Entity
@Table(name = "d_rel_user_blob")
public class DRelUserBlob extends BaseEntity {

	private static final long serialVersionUID = 1L;
	private DBlobStore DBlobStore;
	private DUserApp DUserApp;

	public DRelUserBlob() {
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_id_blob", nullable = false)
	public DBlobStore getDBlobStore() {
		return this.DBlobStore;
	}

	public void setDBlobStore(DBlobStore DBlobStore) {
		this.DBlobStore = DBlobStore;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_id_user", nullable = false)
	public DUserApp getDUserApp() {
		return this.DUserApp;
	}

	public void setDUserApp(DUserApp DUserApp) {
		this.DUserApp = DUserApp;
	}

}
