package com.vince.boot.demo.webapp.be.entity;
// Generated 4-ott-2017 15.34.34 by Hibernate Tools 3.2.2.GA

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DRoleFunction generated by hbm2java
 */
@Entity
@Table(name = "d_role_function")
public class DRoleFunction extends BaseEntity {

	private static final long serialVersionUID = 1L;
	private DRoleUser DRoleUser;

	public DRoleFunction() {
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id", unique = true, nullable = false, insertable = false, updatable = false)
	public DRoleUser getDRoleUser() {
		return this.DRoleUser;
	}

	public void setDRoleUser(DRoleUser DRoleUser) {
		this.DRoleUser = DRoleUser;
	}

}
