package com.vince.boot.demo.webapp.be.entity;
// Generated 4-ott-2017 15.34.34 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DTypeDocument generated by hbm2java
 */
@Entity
@Table(name = "d_type_document", uniqueConstraints = @UniqueConstraint(columnNames = "type_code"))
public class DTypeDocument extends BaseEntity {

	private static final long serialVersionUID = 1L;

	private String typeCode;
	private String typeDescription;

	private Set<DBlobStore> DBlobStores = new HashSet<DBlobStore>(0);

	public DTypeDocument() {
	}

	@Column(name = "type_code", unique = true, nullable = false, length = 20)
	public String getTypeCode() {
		return this.typeCode;
	}

	public void setTypeCode(String typeCode) {
		this.typeCode = typeCode;
	}

	@Column(name = "type_description", nullable = false, length = 100)
	public String getTypeDescription() {
		return this.typeDescription;
	}

	public void setTypeDescription(String typeDescription) {
		this.typeDescription = typeDescription;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "DTypeDocument")
	public Set<DBlobStore> getDBlobStores() {
		return this.DBlobStores;
	}

	public void setDBlobStores(Set<DBlobStore> DBlobStores) {
		this.DBlobStores = DBlobStores;
	}

}
