package com.vince.boot.demo.webapp.be.entity;
// Generated 4-ott-2017 15.34.34 by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.vince.boot.demo.webapp.be.service.impl.CommonAppRepositoryImpl;

/**
 * DRelClientBlob generated by hbm2java
 */
@Entity
@Table(name = "d_rel_client_blob")
public class RelClientBlob extends BaseEntity {

	private static final long serialVersionUID = 1L;
	private ClientApp clientApp;
	private BlobStore blobStore;

	public RelClientBlob() {
	}
	
	public RelClientBlob(Long id) {
		super.id = id;
	}

	public RelClientBlob(ClientApp clientApp, BlobStore blobStore) {
		setClientApp(clientApp);
		setBlobStore(blobStore);
		if(this.isNew()) {
			setTimeInsert(clientApp.getTimeInsert()!=null ? clientApp.getTimeInsert() : new Date());
			setUserInsert(clientApp.getUserInsert()!=null ? clientApp.getUserInsert() : CommonAppRepositoryImpl.USER_SYSTEM);
			setYearRefer(clientApp.getYearRefer()!=null ? clientApp.getYearRefer() : new Date());
		}else {
			setTimeUpdate(clientApp.getTimeUpdate());
			setUserUpdate(clientApp.getUserUpdate());
		}
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_id_client", nullable = false)
	public ClientApp getClientApp() {
		return this.clientApp;
	}

	public void setClientApp(ClientApp clientApp) {
		this.clientApp = clientApp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_id_blob", nullable = false)
	public BlobStore getBlobStore() {
		return this.blobStore;
	}

	public void setBlobStore(BlobStore blobStore) {
		this.blobStore = blobStore;
	}

}
