package com.vince.boot.demo.webapp.be.entity;
// Generated 4-ott-2017 15.34.34 by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.vince.boot.demo.webapp.be.service.impl.CommonAppRepositoryImpl;

/**
 * DRelOrderBlob generated by hbm2java
 */
@Entity
@Table(name = "d_rel_order_blob")
public class RelOrderBlob extends BaseEntity {

	private static final long serialVersionUID = 1L;
	private OrderJob orderJob;
	private BlobStore blobStore;

	public RelOrderBlob() {
	}
	public RelOrderBlob(Long id) {
		super.id = id;
	}

	/**
	 * costructor and managing null pointer for time e user inser
	 * @param orderJob
	 * @param blobStore
	 */
	public RelOrderBlob(OrderJob orderJob, BlobStore blobStore) {
		setOrderJob(orderJob);
		setBlobStore(blobStore);
		if(this.isNew()) {
			setTimeInsert(orderJob.getTimeInsert()!=null ? orderJob.getTimeInsert() : new Date());
			setUserInsert(orderJob.getUserInsert()!=null ? orderJob.getUserInsert() : CommonAppRepositoryImpl.USER_SYSTEM);
			setYearRefer(orderJob.getYearRefer()!=null ? orderJob.getYearRefer() : new Date());
		}else {
			setTimeUpdate(orderJob.getTimeUpdate());
			setUserUpdate(orderJob.getUserUpdate());
		}
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_id_order", nullable = false)
	public OrderJob getOrderJob() {
		return this.orderJob;
	}

	public void setOrderJob(OrderJob orderJob) {
		this.orderJob = orderJob;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_id_blob", nullable = false)
	public BlobStore getBlobStore() {
		return this.blobStore;
	}

	public void setBlobStore(BlobStore blobStore) {
		this.blobStore = blobStore;
	}

}
