/*
 * This file is generated by jOOQ.
*/
package com.vince.boot.demo.webapp.jooq.tables;


import com.vince.boot.demo.webapp.jooq.Demo;
import com.vince.boot.demo.webapp.jooq.Indexes;
import com.vince.boot.demo.webapp.jooq.tables.records.DBlobStoreHRecord;

import java.sql.Date;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DBlobStoreH extends TableImpl<DBlobStoreHRecord> {

    private static final long serialVersionUID = -1509388664;

    /**
     * The reference instance of <code>demo.d_blob_store_h</code>
     */
    public static final DBlobStoreH D_BLOB_STORE_H = new DBlobStoreH();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DBlobStoreHRecord> getRecordType() {
        return DBlobStoreHRecord.class;
    }

    /**
     * The column <code>demo.d_blob_store_h.user_insert</code>.
     */
    public final TableField<DBlobStoreHRecord, Integer> USER_INSERT = createField("user_insert", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>demo.d_blob_store_h.user_update</code>.
     */
    public final TableField<DBlobStoreHRecord, Integer> USER_UPDATE = createField("user_update", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>demo.d_blob_store_h.time_insert</code>.
     */
    public final TableField<DBlobStoreHRecord, Timestamp> TIME_INSERT = createField("time_insert", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>demo.d_blob_store_h.time_update</code>.
     */
    public final TableField<DBlobStoreHRecord, Timestamp> TIME_UPDATE = createField("time_update", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>demo.d_blob_store_h.id</code>.
     */
    public final TableField<DBlobStoreHRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>demo.d_blob_store_h.filename</code>.
     */
    public final TableField<DBlobStoreHRecord, String> FILENAME = createField("filename", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>demo.d_blob_store_h.flag_active</code>.
     */
    public final TableField<DBlobStoreHRecord, String> FLAG_ACTIVE = createField("flag_active", org.jooq.impl.SQLDataType.CHAR(1), this, "");

    /**
     * The column <code>demo.d_blob_store_h.blob_data</code>.
     */
    public final TableField<DBlobStoreHRecord, byte[]> BLOB_DATA = createField("blob_data", org.jooq.impl.SQLDataType.BLOB, this, "");

    /**
     * The column <code>demo.d_blob_store_h.fk_id_type</code>.
     */
    public final TableField<DBlobStoreHRecord, Long> FK_ID_TYPE = createField("fk_id_type", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>demo.d_blob_store_h.description</code>.
     */
    public final TableField<DBlobStoreHRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>demo.d_blob_store_h.content_type</code>.
     */
    public final TableField<DBlobStoreHRecord, String> CONTENT_TYPE = createField("content_type", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>demo.d_blob_store_h.year_refer</code>.
     */
    public final TableField<DBlobStoreHRecord, Date> YEAR_REFER = createField("year_refer", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>demo.d_blob_store_h.crud_type</code>.
     */
    public final TableField<DBlobStoreHRecord, String> CRUD_TYPE = createField("crud_type", org.jooq.impl.SQLDataType.CHAR(1).nullable(false), this, "");

    /**
     * Create a <code>demo.d_blob_store_h</code> table reference
     */
    public DBlobStoreH() {
        this(DSL.name("d_blob_store_h"), null);
    }

    /**
     * Create an aliased <code>demo.d_blob_store_h</code> table reference
     */
    public DBlobStoreH(String alias) {
        this(DSL.name(alias), D_BLOB_STORE_H);
    }

    /**
     * Create an aliased <code>demo.d_blob_store_h</code> table reference
     */
    public DBlobStoreH(Name alias) {
        this(alias, D_BLOB_STORE_H);
    }

    private DBlobStoreH(Name alias, Table<DBlobStoreHRecord> aliased) {
        this(alias, aliased, null);
    }

    private DBlobStoreH(Name alias, Table<DBlobStoreHRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Demo.DEMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.D_BLOB_STORE_H_IX_RELATIONSHIP35);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DBlobStoreH as(String alias) {
        return new DBlobStoreH(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DBlobStoreH as(Name alias) {
        return new DBlobStoreH(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DBlobStoreH rename(String name) {
        return new DBlobStoreH(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DBlobStoreH rename(Name name) {
        return new DBlobStoreH(name, null);
    }
}
