/*
 * This file is generated by jOOQ.
*/
package com.vince.boot.demo.webapp.jooq.tables;


import com.vince.boot.demo.webapp.jooq.Demo;
import com.vince.boot.demo.webapp.jooq.Indexes;
import com.vince.boot.demo.webapp.jooq.Keys;
import com.vince.boot.demo.webapp.jooq.tables.records.DClientAppRecord;

import java.sql.Date;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DClientApp extends TableImpl<DClientAppRecord> {

    private static final long serialVersionUID = -1992567777;

    /**
     * The reference instance of <code>demo.d_client_app</code>
     */
    public static final DClientApp D_CLIENT_APP = new DClientApp();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DClientAppRecord> getRecordType() {
        return DClientAppRecord.class;
    }

    /**
     * The column <code>demo.d_client_app.user_insert</code>.
     */
    public final TableField<DClientAppRecord, String> USER_INSERT = createField("user_insert", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>demo.d_client_app.user_update</code>.
     */
    public final TableField<DClientAppRecord, String> USER_UPDATE = createField("user_update", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>demo.d_client_app.time_insert</code>.
     */
    public final TableField<DClientAppRecord, Timestamp> TIME_INSERT = createField("time_insert", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>demo.d_client_app.time_update</code>.
     */
    public final TableField<DClientAppRecord, Timestamp> TIME_UPDATE = createField("time_update", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>demo.d_client_app.id</code>.
     */
    public final TableField<DClientAppRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>demo.d_client_app.name</code>.
     */
    public final TableField<DClientAppRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>demo.d_client_app.piva</code>.
     */
    public final TableField<DClientAppRecord, String> PIVA = createField("piva", org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>demo.d_client_app.address</code>.
     */
    public final TableField<DClientAppRecord, String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.VARCHAR(2000).nullable(false), this, "");

    /**
     * The column <code>demo.d_client_app.zipcode</code>.
     */
    public final TableField<DClientAppRecord, String> ZIPCODE = createField("zipcode", org.jooq.impl.SQLDataType.VARCHAR(5).nullable(false), this, "");

    /**
     * The column <code>demo.d_client_app.notes</code>.
     */
    public final TableField<DClientAppRecord, String> NOTES = createField("notes", org.jooq.impl.SQLDataType.VARCHAR(2000).nullable(false), this, "");

    /**
     * The column <code>demo.d_client_app.phone</code>.
     */
    public final TableField<DClientAppRecord, String> PHONE = createField("phone", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>demo.d_client_app.email</code>.
     */
    public final TableField<DClientAppRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>demo.d_client_app.year_refer</code>.
     */
    public final TableField<DClientAppRecord, Date> YEAR_REFER = createField("year_refer", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * Create a <code>demo.d_client_app</code> table reference
     */
    public DClientApp() {
        this(DSL.name("d_client_app"), null);
    }

    /**
     * Create an aliased <code>demo.d_client_app</code> table reference
     */
    public DClientApp(String alias) {
        this(DSL.name(alias), D_CLIENT_APP);
    }

    /**
     * Create an aliased <code>demo.d_client_app</code> table reference
     */
    public DClientApp(Name alias) {
        this(alias, D_CLIENT_APP);
    }

    private DClientApp(Name alias, Table<DClientAppRecord> aliased) {
        this(alias, aliased, null);
    }

    private DClientApp(Name alias, Table<DClientAppRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Demo.DEMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.D_CLIENT_APP_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DClientAppRecord> getPrimaryKey() {
        return Keys.KEY_D_CLIENT_APP_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DClientAppRecord>> getKeys() {
        return Arrays.<UniqueKey<DClientAppRecord>>asList(Keys.KEY_D_CLIENT_APP_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DClientApp as(String alias) {
        return new DClientApp(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DClientApp as(Name alias) {
        return new DClientApp(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DClientApp rename(String name) {
        return new DClientApp(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DClientApp rename(Name name) {
        return new DClientApp(name, null);
    }
}
