/*
 * This file is generated by jOOQ.
*/
package com.vince.boot.demo.webapp.jooq.tables;


import com.vince.boot.demo.webapp.jooq.Demo;
import com.vince.boot.demo.webapp.jooq.tables.records.DClientHRecord;

import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DClientH extends TableImpl<DClientHRecord> {

    private static final long serialVersionUID = 1854824936;

    /**
     * The reference instance of <code>demo.d_client_h</code>
     */
    public static final DClientH D_CLIENT_H = new DClientH();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DClientHRecord> getRecordType() {
        return DClientHRecord.class;
    }

    /**
     * The column <code>demo.d_client_h.user_insert</code>.
     */
    public final TableField<DClientHRecord, Integer> USER_INSERT = createField("user_insert", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>demo.d_client_h.user_update</code>.
     */
    public final TableField<DClientHRecord, Integer> USER_UPDATE = createField("user_update", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>demo.d_client_h.time_insert</code>.
     */
    public final TableField<DClientHRecord, Timestamp> TIME_INSERT = createField("time_insert", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>demo.d_client_h.time_update</code>.
     */
    public final TableField<DClientHRecord, Timestamp> TIME_UPDATE = createField("time_update", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>demo.d_client_h.id</code>.
     */
    public final TableField<DClientHRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>demo.d_client_h.name</code>.
     */
    public final TableField<DClientHRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>demo.d_client_h.piva</code>.
     */
    public final TableField<DClientHRecord, String> PIVA = createField("piva", org.jooq.impl.SQLDataType.VARCHAR(16), this, "");

    /**
     * The column <code>demo.d_client_h.address</code>.
     */
    public final TableField<DClientHRecord, String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>demo.d_client_h.zipcode</code>.
     */
    public final TableField<DClientHRecord, String> ZIPCODE = createField("zipcode", org.jooq.impl.SQLDataType.VARCHAR(5), this, "");

    /**
     * The column <code>demo.d_client_h.notes</code>.
     */
    public final TableField<DClientHRecord, String> NOTES = createField("notes", org.jooq.impl.SQLDataType.VARCHAR(2000), this, "");

    /**
     * The column <code>demo.d_client_h.phone</code>.
     */
    public final TableField<DClientHRecord, String> PHONE = createField("phone", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>demo.d_client_h.email</code>.
     */
    public final TableField<DClientHRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>demo.d_client_h.year_refer</code>.
     */
    public final TableField<DClientHRecord, Date> YEAR_REFER = createField("year_refer", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>demo.d_client_h.crud_type</code>.
     */
    public final TableField<DClientHRecord, String> CRUD_TYPE = createField("crud_type", org.jooq.impl.SQLDataType.CHAR(1).nullable(false), this, "");

    /**
     * Create a <code>demo.d_client_h</code> table reference
     */
    public DClientH() {
        this(DSL.name("d_client_h"), null);
    }

    /**
     * Create an aliased <code>demo.d_client_h</code> table reference
     */
    public DClientH(String alias) {
        this(DSL.name(alias), D_CLIENT_H);
    }

    /**
     * Create an aliased <code>demo.d_client_h</code> table reference
     */
    public DClientH(Name alias) {
        this(alias, D_CLIENT_H);
    }

    private DClientH(Name alias, Table<DClientHRecord> aliased) {
        this(alias, aliased, null);
    }

    private DClientH(Name alias, Table<DClientHRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Demo.DEMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DClientH as(String alias) {
        return new DClientH(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DClientH as(Name alias) {
        return new DClientH(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DClientH rename(String name) {
        return new DClientH(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DClientH rename(Name name) {
        return new DClientH(name, null);
    }
}
