/*
 * This file is generated by jOOQ.
*/
package com.vince.boot.demo.webapp.jooq.tables;


import com.vince.boot.demo.webapp.jooq.Demo;
import com.vince.boot.demo.webapp.jooq.tables.records.DGeoLocalHRecord;

import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DGeoLocalH extends TableImpl<DGeoLocalHRecord> {

    private static final long serialVersionUID = 1742170618;

    /**
     * The reference instance of <code>demo.d_geo_local_h</code>
     */
    public static final DGeoLocalH D_GEO_LOCAL_H = new DGeoLocalH();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DGeoLocalHRecord> getRecordType() {
        return DGeoLocalHRecord.class;
    }

    /**
     * The column <code>demo.d_geo_local_h.user_insert</code>.
     */
    public final TableField<DGeoLocalHRecord, Integer> USER_INSERT = createField("user_insert", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>demo.d_geo_local_h.user_update</code>.
     */
    public final TableField<DGeoLocalHRecord, Integer> USER_UPDATE = createField("user_update", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>demo.d_geo_local_h.time_insert</code>.
     */
    public final TableField<DGeoLocalHRecord, Timestamp> TIME_INSERT = createField("time_insert", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>demo.d_geo_local_h.time_update</code>.
     */
    public final TableField<DGeoLocalHRecord, Timestamp> TIME_UPDATE = createField("time_update", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>demo.d_geo_local_h.id</code>.
     */
    public final TableField<DGeoLocalHRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>demo.d_geo_local_h.year_refer</code>.
     */
    public final TableField<DGeoLocalHRecord, Date> YEAR_REFER = createField("year_refer", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>demo.d_geo_local_h.crud_type</code>.
     */
    public final TableField<DGeoLocalHRecord, String> CRUD_TYPE = createField("crud_type", org.jooq.impl.SQLDataType.CHAR(1).nullable(false), this, "");

    /**
     * Create a <code>demo.d_geo_local_h</code> table reference
     */
    public DGeoLocalH() {
        this(DSL.name("d_geo_local_h"), null);
    }

    /**
     * Create an aliased <code>demo.d_geo_local_h</code> table reference
     */
    public DGeoLocalH(String alias) {
        this(DSL.name(alias), D_GEO_LOCAL_H);
    }

    /**
     * Create an aliased <code>demo.d_geo_local_h</code> table reference
     */
    public DGeoLocalH(Name alias) {
        this(alias, D_GEO_LOCAL_H);
    }

    private DGeoLocalH(Name alias, Table<DGeoLocalHRecord> aliased) {
        this(alias, aliased, null);
    }

    private DGeoLocalH(Name alias, Table<DGeoLocalHRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Demo.DEMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DGeoLocalH as(String alias) {
        return new DGeoLocalH(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DGeoLocalH as(Name alias) {
        return new DGeoLocalH(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DGeoLocalH rename(String name) {
        return new DGeoLocalH(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DGeoLocalH rename(Name name) {
        return new DGeoLocalH(name, null);
    }
}
