/*
 * This file is generated by jOOQ.
*/
package com.vince.boot.demo.webapp.jooq.tables;


import com.vince.boot.demo.webapp.jooq.Demo;
import com.vince.boot.demo.webapp.jooq.tables.records.DOrderJobHRecord;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DOrderJobH extends TableImpl<DOrderJobHRecord> {

    private static final long serialVersionUID = -865171408;

    /**
     * The reference instance of <code>demo.d_order_job_h</code>
     */
    public static final DOrderJobH D_ORDER_JOB_H = new DOrderJobH();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DOrderJobHRecord> getRecordType() {
        return DOrderJobHRecord.class;
    }

    /**
     * The column <code>demo.d_order_job_h.user_insert</code>.
     */
    public final TableField<DOrderJobHRecord, String> USER_INSERT = createField("user_insert", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>demo.d_order_job_h.user_update</code>.
     */
    public final TableField<DOrderJobHRecord, String> USER_UPDATE = createField("user_update", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>demo.d_order_job_h.time_insert</code>.
     */
    public final TableField<DOrderJobHRecord, Timestamp> TIME_INSERT = createField("time_insert", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>demo.d_order_job_h.time_update</code>.
     */
    public final TableField<DOrderJobHRecord, Timestamp> TIME_UPDATE = createField("time_update", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>demo.d_order_job_h.id</code>.
     */
    public final TableField<DOrderJobHRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>demo.d_order_job_h.fk_id_client</code>.
     */
    public final TableField<DOrderJobHRecord, Long> FK_ID_CLIENT = createField("fk_id_client", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>demo.d_order_job_h.notes</code>.
     */
    public final TableField<DOrderJobHRecord, String> NOTES = createField("notes", org.jooq.impl.SQLDataType.VARCHAR(2000), this, "");

    /**
     * The column <code>demo.d_order_job_h.code_order</code>.
     */
    public final TableField<DOrderJobHRecord, String> CODE_ORDER = createField("code_order", org.jooq.impl.SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>demo.d_order_job_h.data_scadenza</code>.
     */
    public final TableField<DOrderJobHRecord, Timestamp> DATA_SCADENZA = createField("data_scadenza", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>demo.d_order_job_h.year_refer</code>.
     */
    public final TableField<DOrderJobHRecord, Date> YEAR_REFER = createField("year_refer", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>demo.d_order_job_h.pre_amount</code>.
     */
    public final TableField<DOrderJobHRecord, BigDecimal> PRE_AMOUNT = createField("pre_amount", org.jooq.impl.SQLDataType.DECIMAL(10, 2), this, "");

    /**
     * The column <code>demo.d_order_job_h.final_amount</code>.
     */
    public final TableField<DOrderJobHRecord, BigDecimal> FINAL_AMOUNT = createField("final_amount", org.jooq.impl.SQLDataType.DECIMAL(10, 2), this, "");

    /**
     * The column <code>demo.d_order_job_h.flag_active</code>.
     */
    public final TableField<DOrderJobHRecord, String> FLAG_ACTIVE = createField("flag_active", org.jooq.impl.SQLDataType.CHAR(1), this, "");

    /**
     * The column <code>demo.d_order_job_h.crud_type</code>.
     */
    public final TableField<DOrderJobHRecord, String> CRUD_TYPE = createField("crud_type", org.jooq.impl.SQLDataType.CHAR(1).nullable(false), this, "");

    /**
     * The column <code>demo.d_order_job_h.address</code>.
     */
    public final TableField<DOrderJobHRecord, byte[]> ADDRESS = createField("address", org.jooq.impl.SQLDataType.VARBINARY(200), this, "");

    /**
     * Create a <code>demo.d_order_job_h</code> table reference
     */
    public DOrderJobH() {
        this(DSL.name("d_order_job_h"), null);
    }

    /**
     * Create an aliased <code>demo.d_order_job_h</code> table reference
     */
    public DOrderJobH(String alias) {
        this(DSL.name(alias), D_ORDER_JOB_H);
    }

    /**
     * Create an aliased <code>demo.d_order_job_h</code> table reference
     */
    public DOrderJobH(Name alias) {
        this(alias, D_ORDER_JOB_H);
    }

    private DOrderJobH(Name alias, Table<DOrderJobHRecord> aliased) {
        this(alias, aliased, null);
    }

    private DOrderJobH(Name alias, Table<DOrderJobHRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Demo.DEMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DOrderJobH as(String alias) {
        return new DOrderJobH(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DOrderJobH as(Name alias) {
        return new DOrderJobH(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DOrderJobH rename(String name) {
        return new DOrderJobH(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DOrderJobH rename(Name name) {
        return new DOrderJobH(name, null);
    }
}
