/*
 * This file is generated by jOOQ.
*/
package com.vince.boot.demo.webapp.jooq.tables;


import com.vince.boot.demo.webapp.jooq.Demo;
import com.vince.boot.demo.webapp.jooq.Indexes;
import com.vince.boot.demo.webapp.jooq.Keys;
import com.vince.boot.demo.webapp.jooq.tables.records.DRelOrderBlobRecord;

import java.sql.Date;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DRelOrderBlob extends TableImpl<DRelOrderBlobRecord> {

    private static final long serialVersionUID = 163556559;

    /**
     * The reference instance of <code>demo.d_rel_order_blob</code>
     */
    public static final DRelOrderBlob D_REL_ORDER_BLOB = new DRelOrderBlob();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DRelOrderBlobRecord> getRecordType() {
        return DRelOrderBlobRecord.class;
    }

    /**
     * The column <code>demo.d_rel_order_blob.fk_id_order</code>.
     */
    public final TableField<DRelOrderBlobRecord, Long> FK_ID_ORDER = createField("fk_id_order", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>demo.d_rel_order_blob.fk_id_blob</code>.
     */
    public final TableField<DRelOrderBlobRecord, Long> FK_ID_BLOB = createField("fk_id_blob", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>demo.d_rel_order_blob.id</code>.
     */
    public final TableField<DRelOrderBlobRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>demo.d_rel_order_blob.user_insert</code>.
     */
    public final TableField<DRelOrderBlobRecord, String> USER_INSERT = createField("user_insert", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>demo.d_rel_order_blob.user_update</code>.
     */
    public final TableField<DRelOrderBlobRecord, String> USER_UPDATE = createField("user_update", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>demo.d_rel_order_blob.time_insert</code>.
     */
    public final TableField<DRelOrderBlobRecord, Timestamp> TIME_INSERT = createField("time_insert", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>demo.d_rel_order_blob.time_update</code>.
     */
    public final TableField<DRelOrderBlobRecord, Timestamp> TIME_UPDATE = createField("time_update", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>demo.d_rel_order_blob.year_refer</code>.
     */
    public final TableField<DRelOrderBlobRecord, Date> YEAR_REFER = createField("year_refer", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * Create a <code>demo.d_rel_order_blob</code> table reference
     */
    public DRelOrderBlob() {
        this(DSL.name("d_rel_order_blob"), null);
    }

    /**
     * Create an aliased <code>demo.d_rel_order_blob</code> table reference
     */
    public DRelOrderBlob(String alias) {
        this(DSL.name(alias), D_REL_ORDER_BLOB);
    }

    /**
     * Create an aliased <code>demo.d_rel_order_blob</code> table reference
     */
    public DRelOrderBlob(Name alias) {
        this(alias, D_REL_ORDER_BLOB);
    }

    private DRelOrderBlob(Name alias, Table<DRelOrderBlobRecord> aliased) {
        this(alias, aliased, null);
    }

    private DRelOrderBlob(Name alias, Table<DRelOrderBlobRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Demo.DEMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.D_REL_ORDER_BLOB_IX_RELATIONSHIP30, Indexes.D_REL_ORDER_BLOB_IX_RELATIONSHIP31, Indexes.D_REL_ORDER_BLOB_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<DRelOrderBlobRecord, Long> getIdentity() {
        return Keys.IDENTITY_D_REL_ORDER_BLOB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DRelOrderBlobRecord> getPrimaryKey() {
        return Keys.KEY_D_REL_ORDER_BLOB_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DRelOrderBlobRecord>> getKeys() {
        return Arrays.<UniqueKey<DRelOrderBlobRecord>>asList(Keys.KEY_D_REL_ORDER_BLOB_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<DRelOrderBlobRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DRelOrderBlobRecord, ?>>asList(Keys.RELATIONSHIP30, Keys.RELATIONSHIP31);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRelOrderBlob as(String alias) {
        return new DRelOrderBlob(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRelOrderBlob as(Name alias) {
        return new DRelOrderBlob(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DRelOrderBlob rename(String name) {
        return new DRelOrderBlob(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DRelOrderBlob rename(Name name) {
        return new DRelOrderBlob(name, null);
    }
}
