/*
 * This file is generated by jOOQ.
*/
package com.vince.boot.demo.webapp.jooq.tables;


import com.vince.boot.demo.webapp.jooq.Demo;
import com.vince.boot.demo.webapp.jooq.Indexes;
import com.vince.boot.demo.webapp.jooq.Keys;
import com.vince.boot.demo.webapp.jooq.tables.records.DRelUserBlobRecord;

import java.sql.Date;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DRelUserBlob extends TableImpl<DRelUserBlobRecord> {

    private static final long serialVersionUID = -663339416;

    /**
     * The reference instance of <code>demo.d_rel_user_blob</code>
     */
    public static final DRelUserBlob D_REL_USER_BLOB = new DRelUserBlob();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DRelUserBlobRecord> getRecordType() {
        return DRelUserBlobRecord.class;
    }

    /**
     * The column <code>demo.d_rel_user_blob.fk_id_user</code>.
     */
    public final TableField<DRelUserBlobRecord, Long> FK_ID_USER = createField("fk_id_user", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>demo.d_rel_user_blob.fk_id_blob</code>.
     */
    public final TableField<DRelUserBlobRecord, Long> FK_ID_BLOB = createField("fk_id_blob", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>demo.d_rel_user_blob.id</code>.
     */
    public final TableField<DRelUserBlobRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>demo.d_rel_user_blob.user_insert</code>.
     */
    public final TableField<DRelUserBlobRecord, String> USER_INSERT = createField("user_insert", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>demo.d_rel_user_blob.user_update</code>.
     */
    public final TableField<DRelUserBlobRecord, String> USER_UPDATE = createField("user_update", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>demo.d_rel_user_blob.time_update</code>.
     */
    public final TableField<DRelUserBlobRecord, Timestamp> TIME_UPDATE = createField("time_update", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>demo.d_rel_user_blob.time_insert</code>.
     */
    public final TableField<DRelUserBlobRecord, Timestamp> TIME_INSERT = createField("time_insert", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>demo.d_rel_user_blob.year_refer</code>.
     */
    public final TableField<DRelUserBlobRecord, Date> YEAR_REFER = createField("year_refer", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * Create a <code>demo.d_rel_user_blob</code> table reference
     */
    public DRelUserBlob() {
        this(DSL.name("d_rel_user_blob"), null);
    }

    /**
     * Create an aliased <code>demo.d_rel_user_blob</code> table reference
     */
    public DRelUserBlob(String alias) {
        this(DSL.name(alias), D_REL_USER_BLOB);
    }

    /**
     * Create an aliased <code>demo.d_rel_user_blob</code> table reference
     */
    public DRelUserBlob(Name alias) {
        this(alias, D_REL_USER_BLOB);
    }

    private DRelUserBlob(Name alias, Table<DRelUserBlobRecord> aliased) {
        this(alias, aliased, null);
    }

    private DRelUserBlob(Name alias, Table<DRelUserBlobRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Demo.DEMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.D_REL_USER_BLOB_IX_RELATIONSHIP20, Indexes.D_REL_USER_BLOB_IX_RELATIONSHIP22, Indexes.D_REL_USER_BLOB_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<DRelUserBlobRecord, Long> getIdentity() {
        return Keys.IDENTITY_D_REL_USER_BLOB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DRelUserBlobRecord> getPrimaryKey() {
        return Keys.KEY_D_REL_USER_BLOB_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DRelUserBlobRecord>> getKeys() {
        return Arrays.<UniqueKey<DRelUserBlobRecord>>asList(Keys.KEY_D_REL_USER_BLOB_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<DRelUserBlobRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DRelUserBlobRecord, ?>>asList(Keys.RELATIONSHIP22, Keys.RELATIONSHIP20);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRelUserBlob as(String alias) {
        return new DRelUserBlob(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRelUserBlob as(Name alias) {
        return new DRelUserBlob(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DRelUserBlob rename(String name) {
        return new DRelUserBlob(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DRelUserBlob rename(Name name) {
        return new DRelUserBlob(name, null);
    }
}
