/*
 * This file is generated by jOOQ.
*/
package com.vince.boot.demo.webapp.jooq.tables;


import com.vince.boot.demo.webapp.jooq.Demo;
import com.vince.boot.demo.webapp.jooq.Indexes;
import com.vince.boot.demo.webapp.jooq.tables.records.DRelClientBlobHRecord;

import java.sql.Date;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DRelClientBlobH extends TableImpl<DRelClientBlobHRecord> {

    private static final long serialVersionUID = -2044190119;

    /**
     * The reference instance of <code>demo.d_rel_client_blob_h</code>
     */
    public static final DRelClientBlobH D_REL_CLIENT_BLOB_H = new DRelClientBlobH();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DRelClientBlobHRecord> getRecordType() {
        return DRelClientBlobHRecord.class;
    }

    /**
     * The column <code>demo.d_rel_client_blob_h.fk_id_client</code>.
     */
    public final TableField<DRelClientBlobHRecord, Long> FK_ID_CLIENT = createField("fk_id_client", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>demo.d_rel_client_blob_h.fk_id_blob</code>.
     */
    public final TableField<DRelClientBlobHRecord, Long> FK_ID_BLOB = createField("fk_id_blob", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>demo.d_rel_client_blob_h.time_insert</code>.
     */
    public final TableField<DRelClientBlobHRecord, Timestamp> TIME_INSERT = createField("time_insert", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>demo.d_rel_client_blob_h.time_update</code>.
     */
    public final TableField<DRelClientBlobHRecord, Timestamp> TIME_UPDATE = createField("time_update", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>demo.d_rel_client_blob_h.user_insert</code>.
     */
    public final TableField<DRelClientBlobHRecord, String> USER_INSERT = createField("user_insert", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>demo.d_rel_client_blob_h.user_update</code>.
     */
    public final TableField<DRelClientBlobHRecord, String> USER_UPDATE = createField("user_update", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>demo.d_rel_client_blob_h.id</code>.
     */
    public final TableField<DRelClientBlobHRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>demo.d_rel_client_blob_h.year_refer</code>.
     */
    public final TableField<DRelClientBlobHRecord, Date> YEAR_REFER = createField("year_refer", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>demo.d_rel_client_blob_h.crud_type</code>.
     */
    public final TableField<DRelClientBlobHRecord, String> CRUD_TYPE = createField("crud_type", org.jooq.impl.SQLDataType.CHAR(1).nullable(false), this, "");

    /**
     * Create a <code>demo.d_rel_client_blob_h</code> table reference
     */
    public DRelClientBlobH() {
        this(DSL.name("d_rel_client_blob_h"), null);
    }

    /**
     * Create an aliased <code>demo.d_rel_client_blob_h</code> table reference
     */
    public DRelClientBlobH(String alias) {
        this(DSL.name(alias), D_REL_CLIENT_BLOB_H);
    }

    /**
     * Create an aliased <code>demo.d_rel_client_blob_h</code> table reference
     */
    public DRelClientBlobH(Name alias) {
        this(alias, D_REL_CLIENT_BLOB_H);
    }

    private DRelClientBlobH(Name alias, Table<DRelClientBlobHRecord> aliased) {
        this(alias, aliased, null);
    }

    private DRelClientBlobH(Name alias, Table<DRelClientBlobHRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Demo.DEMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.D_REL_CLIENT_BLOB_H_IX_RELATIONSHIP32, Indexes.D_REL_CLIENT_BLOB_H_IX_RELATIONSHIP33);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRelClientBlobH as(String alias) {
        return new DRelClientBlobH(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRelClientBlobH as(Name alias) {
        return new DRelClientBlobH(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DRelClientBlobH rename(String name) {
        return new DRelClientBlobH(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DRelClientBlobH rename(Name name) {
        return new DRelClientBlobH(name, null);
    }
}
