/*
 * This file is generated by jOOQ.
*/
package com.vince.boot.demo.webapp.jooq.tables;


import com.vince.boot.demo.webapp.jooq.Demo;
import com.vince.boot.demo.webapp.jooq.Indexes;
import com.vince.boot.demo.webapp.jooq.tables.records.DRelOrderBlobHRecord;

import java.sql.Date;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DRelOrderBlobH extends TableImpl<DRelOrderBlobHRecord> {

    private static final long serialVersionUID = -1973324494;

    /**
     * The reference instance of <code>demo.d_rel_order_blob_h</code>
     */
    public static final DRelOrderBlobH D_REL_ORDER_BLOB_H = new DRelOrderBlobH();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DRelOrderBlobHRecord> getRecordType() {
        return DRelOrderBlobHRecord.class;
    }

    /**
     * The column <code>demo.d_rel_order_blob_h.fk_id_order</code>.
     */
    public final TableField<DRelOrderBlobHRecord, Long> FK_ID_ORDER = createField("fk_id_order", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>demo.d_rel_order_blob_h.fk_id_blob</code>.
     */
    public final TableField<DRelOrderBlobHRecord, Long> FK_ID_BLOB = createField("fk_id_blob", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>demo.d_rel_order_blob_h.id</code>.
     */
    public final TableField<DRelOrderBlobHRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>demo.d_rel_order_blob_h.user_insert</code>.
     */
    public final TableField<DRelOrderBlobHRecord, String> USER_INSERT = createField("user_insert", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>demo.d_rel_order_blob_h.user_update</code>.
     */
    public final TableField<DRelOrderBlobHRecord, String> USER_UPDATE = createField("user_update", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>demo.d_rel_order_blob_h.time_insert</code>.
     */
    public final TableField<DRelOrderBlobHRecord, Timestamp> TIME_INSERT = createField("time_insert", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>demo.d_rel_order_blob_h.time_update</code>.
     */
    public final TableField<DRelOrderBlobHRecord, Timestamp> TIME_UPDATE = createField("time_update", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>demo.d_rel_order_blob_h.year_refer</code>.
     */
    public final TableField<DRelOrderBlobHRecord, Date> YEAR_REFER = createField("year_refer", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>demo.d_rel_order_blob_h.crud_type</code>.
     */
    public final TableField<DRelOrderBlobHRecord, String> CRUD_TYPE = createField("crud_type", org.jooq.impl.SQLDataType.CHAR(1).nullable(false), this, "");

    /**
     * Create a <code>demo.d_rel_order_blob_h</code> table reference
     */
    public DRelOrderBlobH() {
        this(DSL.name("d_rel_order_blob_h"), null);
    }

    /**
     * Create an aliased <code>demo.d_rel_order_blob_h</code> table reference
     */
    public DRelOrderBlobH(String alias) {
        this(DSL.name(alias), D_REL_ORDER_BLOB_H);
    }

    /**
     * Create an aliased <code>demo.d_rel_order_blob_h</code> table reference
     */
    public DRelOrderBlobH(Name alias) {
        this(alias, D_REL_ORDER_BLOB_H);
    }

    private DRelOrderBlobH(Name alias, Table<DRelOrderBlobHRecord> aliased) {
        this(alias, aliased, null);
    }

    private DRelOrderBlobH(Name alias, Table<DRelOrderBlobHRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Demo.DEMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.D_REL_ORDER_BLOB_H_IX_RELATIONSHIP30, Indexes.D_REL_ORDER_BLOB_H_IX_RELATIONSHIP31);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRelOrderBlobH as(String alias) {
        return new DRelOrderBlobH(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRelOrderBlobH as(Name alias) {
        return new DRelOrderBlobH(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DRelOrderBlobH rename(String name) {
        return new DRelOrderBlobH(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DRelOrderBlobH rename(Name name) {
        return new DRelOrderBlobH(name, null);
    }
}
