/*
 * This file is generated by jOOQ.
*/
package com.vince.boot.demo.webapp.jooq.tables;


import com.vince.boot.demo.webapp.jooq.Demo;
import com.vince.boot.demo.webapp.jooq.Indexes;
import com.vince.boot.demo.webapp.jooq.Keys;
import com.vince.boot.demo.webapp.jooq.tables.records.DRoleUserRecord;

import java.sql.Date;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DRoleUser extends TableImpl<DRoleUserRecord> {

    private static final long serialVersionUID = 2106390069;

    /**
     * The reference instance of <code>demo.d_role_user</code>
     */
    public static final DRoleUser D_ROLE_USER = new DRoleUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DRoleUserRecord> getRecordType() {
        return DRoleUserRecord.class;
    }

    /**
     * The column <code>demo.d_role_user.user_insert</code>.
     */
    public final TableField<DRoleUserRecord, String> USER_INSERT = createField("user_insert", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>demo.d_role_user.user_update</code>.
     */
    public final TableField<DRoleUserRecord, String> USER_UPDATE = createField("user_update", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>demo.d_role_user.time_insert</code>.
     */
    public final TableField<DRoleUserRecord, Timestamp> TIME_INSERT = createField("time_insert", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>demo.d_role_user.time_update</code>.
     */
    public final TableField<DRoleUserRecord, Timestamp> TIME_UPDATE = createField("time_update", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>demo.d_role_user.id</code>.
     */
    public final TableField<DRoleUserRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>demo.d_role_user.role_code</code>.
     */
    public final TableField<DRoleUserRecord, String> ROLE_CODE = createField("role_code", org.jooq.impl.SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>demo.d_role_user.role_description</code>.
     */
    public final TableField<DRoleUserRecord, String> ROLE_DESCRIPTION = createField("role_description", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>demo.d_role_user.year_refer</code>.
     */
    public final TableField<DRoleUserRecord, Date> YEAR_REFER = createField("year_refer", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * Create a <code>demo.d_role_user</code> table reference
     */
    public DRoleUser() {
        this(DSL.name("d_role_user"), null);
    }

    /**
     * Create an aliased <code>demo.d_role_user</code> table reference
     */
    public DRoleUser(String alias) {
        this(DSL.name(alias), D_ROLE_USER);
    }

    /**
     * Create an aliased <code>demo.d_role_user</code> table reference
     */
    public DRoleUser(Name alias) {
        this(alias, D_ROLE_USER);
    }

    private DRoleUser(Name alias, Table<DRoleUserRecord> aliased) {
        this(alias, aliased, null);
    }

    private DRoleUser(Name alias, Table<DRoleUserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Demo.DEMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.D_ROLE_USER_PRIMARY, Indexes.D_ROLE_USER_ROLE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DRoleUserRecord> getPrimaryKey() {
        return Keys.KEY_D_ROLE_USER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DRoleUserRecord>> getKeys() {
        return Arrays.<UniqueKey<DRoleUserRecord>>asList(Keys.KEY_D_ROLE_USER_PRIMARY, Keys.KEY_D_ROLE_USER_ROLE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRoleUser as(String alias) {
        return new DRoleUser(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRoleUser as(Name alias) {
        return new DRoleUser(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DRoleUser rename(String name) {
        return new DRoleUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DRoleUser rename(Name name) {
        return new DRoleUser(name, null);
    }
}
