/*
 * This file is generated by jOOQ.
*/
package com.vince.boot.demo.webapp.jooq.tables;


import com.vince.boot.demo.webapp.jooq.Demo;
import com.vince.boot.demo.webapp.jooq.tables.records.DRoleUserHRecord;

import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DRoleUserH extends TableImpl<DRoleUserHRecord> {

    private static final long serialVersionUID = 1314393494;

    /**
     * The reference instance of <code>demo.d_role_user_h</code>
     */
    public static final DRoleUserH D_ROLE_USER_H = new DRoleUserH();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DRoleUserHRecord> getRecordType() {
        return DRoleUserHRecord.class;
    }

    /**
     * The column <code>demo.d_role_user_h.user_insert</code>.
     */
    public final TableField<DRoleUserHRecord, Integer> USER_INSERT = createField("user_insert", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>demo.d_role_user_h.user_update</code>.
     */
    public final TableField<DRoleUserHRecord, Integer> USER_UPDATE = createField("user_update", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>demo.d_role_user_h.time_insert</code>.
     */
    public final TableField<DRoleUserHRecord, Timestamp> TIME_INSERT = createField("time_insert", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>demo.d_role_user_h.time_update</code>.
     */
    public final TableField<DRoleUserHRecord, Timestamp> TIME_UPDATE = createField("time_update", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>demo.d_role_user_h.id</code>.
     */
    public final TableField<DRoleUserHRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>demo.d_role_user_h.role_code</code>.
     */
    public final TableField<DRoleUserHRecord, String> ROLE_CODE = createField("role_code", org.jooq.impl.SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>demo.d_role_user_h.role_description</code>.
     */
    public final TableField<DRoleUserHRecord, String> ROLE_DESCRIPTION = createField("role_description", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>demo.d_role_user_h.year_refer</code>.
     */
    public final TableField<DRoleUserHRecord, Date> YEAR_REFER = createField("year_refer", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>demo.d_role_user_h.crud_type</code>.
     */
    public final TableField<DRoleUserHRecord, String> CRUD_TYPE = createField("crud_type", org.jooq.impl.SQLDataType.CHAR(1).nullable(false), this, "");

    /**
     * Create a <code>demo.d_role_user_h</code> table reference
     */
    public DRoleUserH() {
        this(DSL.name("d_role_user_h"), null);
    }

    /**
     * Create an aliased <code>demo.d_role_user_h</code> table reference
     */
    public DRoleUserH(String alias) {
        this(DSL.name(alias), D_ROLE_USER_H);
    }

    /**
     * Create an aliased <code>demo.d_role_user_h</code> table reference
     */
    public DRoleUserH(Name alias) {
        this(alias, D_ROLE_USER_H);
    }

    private DRoleUserH(Name alias, Table<DRoleUserHRecord> aliased) {
        this(alias, aliased, null);
    }

    private DRoleUserH(Name alias, Table<DRoleUserHRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Demo.DEMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRoleUserH as(String alias) {
        return new DRoleUserH(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRoleUserH as(Name alias) {
        return new DRoleUserH(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DRoleUserH rename(String name) {
        return new DRoleUserH(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DRoleUserH rename(Name name) {
        return new DRoleUserH(name, null);
    }
}
