/*
 * This file is generated by jOOQ.
*/
package com.vince.boot.demo.webapp.jooq.tables;


import com.vince.boot.demo.webapp.jooq.Demo;
import com.vince.boot.demo.webapp.jooq.tables.records.DRoleFunctionHRecord;

import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DRoleFunctionH extends TableImpl<DRoleFunctionHRecord> {

    private static final long serialVersionUID = -102891406;

    /**
     * The reference instance of <code>demo.d_role_function_h</code>
     */
    public static final DRoleFunctionH D_ROLE_FUNCTION_H = new DRoleFunctionH();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DRoleFunctionHRecord> getRecordType() {
        return DRoleFunctionHRecord.class;
    }

    /**
     * The column <code>demo.d_role_function_h.user_insert</code>.
     */
    public final TableField<DRoleFunctionHRecord, Integer> USER_INSERT = createField("user_insert", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>demo.d_role_function_h.user_update</code>.
     */
    public final TableField<DRoleFunctionHRecord, Integer> USER_UPDATE = createField("user_update", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>demo.d_role_function_h.time_insert</code>.
     */
    public final TableField<DRoleFunctionHRecord, Timestamp> TIME_INSERT = createField("time_insert", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>demo.d_role_function_h.time_update</code>.
     */
    public final TableField<DRoleFunctionHRecord, Timestamp> TIME_UPDATE = createField("time_update", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>demo.d_role_function_h.id</code>.
     */
    public final TableField<DRoleFunctionHRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>demo.d_role_function_h.year_refer</code>.
     */
    public final TableField<DRoleFunctionHRecord, Date> YEAR_REFER = createField("year_refer", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>demo.d_role_function_h.crud_type</code>.
     */
    public final TableField<DRoleFunctionHRecord, String> CRUD_TYPE = createField("crud_type", org.jooq.impl.SQLDataType.CHAR(1).nullable(false), this, "");

    /**
     * Create a <code>demo.d_role_function_h</code> table reference
     */
    public DRoleFunctionH() {
        this(DSL.name("d_role_function_h"), null);
    }

    /**
     * Create an aliased <code>demo.d_role_function_h</code> table reference
     */
    public DRoleFunctionH(String alias) {
        this(DSL.name(alias), D_ROLE_FUNCTION_H);
    }

    /**
     * Create an aliased <code>demo.d_role_function_h</code> table reference
     */
    public DRoleFunctionH(Name alias) {
        this(alias, D_ROLE_FUNCTION_H);
    }

    private DRoleFunctionH(Name alias, Table<DRoleFunctionHRecord> aliased) {
        this(alias, aliased, null);
    }

    private DRoleFunctionH(Name alias, Table<DRoleFunctionHRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Demo.DEMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRoleFunctionH as(String alias) {
        return new DRoleFunctionH(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRoleFunctionH as(Name alias) {
        return new DRoleFunctionH(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DRoleFunctionH rename(String name) {
        return new DRoleFunctionH(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DRoleFunctionH rename(Name name) {
        return new DRoleFunctionH(name, null);
    }
}
