package com.vince.boot.demo.webapp.entity;
// Generated 6-ago-2017 19.42.37 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BlobStore generated by hbm2java
 */
@Entity
@Table(name = "d_blob_store")
public class BlobStore extends BaseEntity {
	private static final long serialVersionUID = 1L;

	private TypeDocument typeDocument;
	private String filename;
	private char flagActive;
	private byte[] blobData;
	private String description;
	private String contentType;
	private Set<RelOrderBlob> relOrderBlobs = new HashSet<RelOrderBlob>(0);
	private Set<RelUserBlob> relUserBlobs = new HashSet<RelUserBlob>(0);
	private Set<RelClientBlob> relClientBlobs = new HashSet<RelClientBlob>(0);


	public BlobStore() {

	}
	public BlobStore(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_id_type", nullable = false)
	public TypeDocument getTypeDocument() {
		return this.typeDocument;
	}

	public void setTypeDocument(TypeDocument typeDocument) {
		this.typeDocument = typeDocument;
	}

	@Column(name = "filename", nullable = false, length = 200)
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Column(name = "flag_active", nullable = false, length = 1)
	public char getFlagActive() {
		return this.flagActive;
	}

	public void setFlagActive(char flagActive) {
		this.flagActive = flagActive;
	}

	@Column(name = "blob_data", nullable = false)
	public byte[] getBlobData() {
		return this.blobData;
	}

	public void setBlobData(byte[] blobData) {
		this.blobData = blobData;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "content_type", nullable = false, length = 100)
	public String getContentType() {
		return this.contentType;
	}

	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "blobStore", cascade = CascadeType.ALL)
	public Set<RelOrderBlob> getRelOrderBlobs() {
		return this.relOrderBlobs;
	}

	public void setRelOrderBlobs(Set<RelOrderBlob> relOrderBlobs) {
		this.relOrderBlobs = relOrderBlobs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "blobStore", cascade = CascadeType.ALL)
	public Set<RelUserBlob> getRelUserBlobs() {
		return this.relUserBlobs;
	}

	public void setRelUserBlobs(Set<RelUserBlob> relUserBlobs) {
		this.relUserBlobs = relUserBlobs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "blobStore", cascade = CascadeType.ALL )
	public Set<RelClientBlob> getRelClientBlobs() {
		return this.relClientBlobs;
	}

	public void setRelClientBlobs(Set<RelClientBlob> relClientBlobs) {
		this.relClientBlobs = relClientBlobs;
	}

}
