package com.vince.boot.demo.webapp.entity;
// Generated 4-ott-2017 15.34.34 by Hibernate Tools 3.2.2.GA

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DGeoLocal generated by hbm2java
 */
@Entity
@Table(name = "d_geo_local")
public class DGeoLocal extends BaseEntity {

	private static final long serialVersionUID = 1L;

	public DGeoLocal() {
	}


}
