package com.vince.boot.demo.webapp.entity;
// Generated 4-ott-2017 15.34.34 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DRoleUser generated by hbm2java
 */
@Entity
@Table(name = "d_role_user", uniqueConstraints = @UniqueConstraint(columnNames = "role_code"))
public class DRoleUser extends BaseEntity {

	private static final long serialVersionUID = 1L;

	private String roleCode;
	private String roleDescription;

	private Set<DUserApp> DUserApps = new HashSet<DUserApp>(0);
	private Set<DRoleFunction> DRoleFunctions = new HashSet<DRoleFunction>(0);

	public DRoleUser() {
	}

	@Column(name = "role_code", unique = true, nullable = false, length = 20)
	public String getRoleCode() {
		return this.roleCode;
	}

	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}

	@Column(name = "role_description", nullable = false, length = 100)
	public String getRoleDescription() {
		return this.roleDescription;
	}

	public void setRoleDescription(String roleDescription) {
		this.roleDescription = roleDescription;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "DRoleUser")
	public Set<DUserApp> getDUserApps() {
		return this.DUserApps;
	}

	public void setDUserApps(Set<DUserApp> DUserApps) {
		this.DUserApps = DUserApps;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "DRoleUser")
	public Set<DRoleFunction> getDRoleFunctions() {
		return this.DRoleFunctions;
	}

	public void setDRoleFunctions(Set<DRoleFunction> DRoleFunctions) {
		this.DRoleFunctions = DRoleFunctions;
	}

}
