package com.vince.boot.demo.webapp.entity;
// Generated 4-ott-2017 15.34.34 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DSystemProps generated by hbm2java
 */
@Entity
@Table(name = "d_system_props", uniqueConstraints = @UniqueConstraint(columnNames = "key_prop"))
public class DSystemProps extends BaseEntity {

	private static final long serialVersionUID = 1L;

	private String keyProp;
	private String valueProp;

	public DSystemProps() {
	}

	@Column(name = "key_prop", unique = true, nullable = false, length = 20)
	public String getKeyProp() {
		return this.keyProp;
	}

	public void setKeyProp(String keyProp) {
		this.keyProp = keyProp;
	}

	@Column(name = "value_prop", nullable = false, length = 200)
	public String getValueProp() {
		return this.valueProp;
	}

	public void setValueProp(String valueProp) {
		this.valueProp = valueProp;
	}

}
