package com.vince.boot.demo.webapp.entity;
// Generated 6-ago-2017 19.42.37 by Hibernate Tools 5.2.3.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GeoLocal generated by hbm2java
 */
@Entity
@Table(name = "d_geo_local")
public class GeoLocal implements java.io.Serializable {

	private long id;
	private int userInsert;
	private Integer userUpdate;
	private Date timeInsert;
	private Date timeUpdate;

	public GeoLocal() {
	}

	public GeoLocal(long id, int userInsert, Date timeInsert) {
		this.id = id;
		this.userInsert = userInsert;
		this.timeInsert = timeInsert;
	}

	public GeoLocal(long id, int userInsert, Integer userUpdate, Date timeInsert, Date timeUpdate) {
		this.id = id;
		this.userInsert = userInsert;
		this.userUpdate = userUpdate;
		this.timeInsert = timeInsert;
		this.timeUpdate = timeUpdate;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "user_insert", nullable = false)
	public int getUserInsert() {
		return this.userInsert;
	}

	public void setUserInsert(int userInsert) {
		this.userInsert = userInsert;
	}

	@Column(name = "user_update")
	public Integer getUserUpdate() {
		return this.userUpdate;
	}

	public void setUserUpdate(Integer userUpdate) {
		this.userUpdate = userUpdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_insert", nullable = false, length = 19)
	public Date getTimeInsert() {
		return this.timeInsert;
	}

	public void setTimeInsert(Date timeInsert) {
		this.timeInsert = timeInsert;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_update", length = 19)
	public Date getTimeUpdate() {
		return this.timeUpdate;
	}

	public void setTimeUpdate(Date timeUpdate) {
		this.timeUpdate = timeUpdate;
	}

}
