package com.vince.boot.demo.webapp.entity;
// Generated 28-ago-2017 16.36.04 by Hibernate Tools 5.2.3.Final

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RelClientBlob generated by hbm2java
 */
@Entity
@Table(name = "d_rel_client_blob")
public class RelClientBlob extends BaseEntity {

	private static final long serialVersionUID = 1L;

	private BlobStore blobStore;
	private ClientApp client;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_id_blob", nullable = false)
	public BlobStore getBlobStore() {
		return this.blobStore;
	}

	public void setBlobStore(BlobStore blobStore) {
		this.blobStore = blobStore;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_id_client", nullable = false)
	public ClientApp getClient() {
		return this.client;
	}

	public void setClient(ClientApp client) {
		this.client = client;
	}

}
