package com.vince.boot.demo.webapp.entity;
// Generated 28-ago-2017 16.36.04 by Hibernate Tools 5.2.3.Final

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RelOrderBlob generated by hbm2java
 */
@Entity
@Table(name = "d_rel_order_blob")
public class RelOrderBlob extends BaseEntity {

	private static final long serialVersionUID = 1L;

	private BlobStore blobStore;
	private OrderJob order;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_id_blob", nullable = false)
	public BlobStore getBlobStore() {
		return this.blobStore;
	}

	public void setBlobStore(BlobStore blobStore) {
		this.blobStore = blobStore;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_id_order", nullable = false)
	public OrderJob getOrder() {
		return this.order;
	}

	public void setOrder(OrderJob order) {
		this.order = order;
	}


}
