package com.vince.boot.demo.webapp.entity;
// Generated 28-ago-2017 16.36.04 by Hibernate Tools 5.2.3.Final

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * RoleFunction generated by hbm2java
 */
@Entity
@Table(name = "d_role_function")
public class RoleFunction extends BaseEntity {

	private static final long serialVersionUID = 1L;

	private RoleUser roleUser;

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public RoleUser getRoleUser() {
		return this.roleUser;
	}

	public void setRoleUser(RoleUser roleUser) {
		this.roleUser = roleUser;
	}


}
