package com.vince.boot.demo.webapp.entity;
// Generated 28-ago-2017 16.36.04 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * RoleUser generated by hbm2java
 */
@Entity
@Table(name = "d_role_user", uniqueConstraints = @UniqueConstraint(columnNames = "role_code"))
public class RoleUser extends BaseEntity {
	private static final long serialVersionUID = 1L;

	private String roleCode;
	private String roleDescription;
	private Set<UserApp> users = new HashSet<UserApp>(0);
	private RoleFunction roleFunction;


	public RoleUser(Long id) {
		this.id=id;
	}

	public RoleUser() {
		// TODO Auto-generated constructor stub
	}

	@Column(name = "role_code", unique = true, nullable = false, length = 20)
	public String getRoleCode() {
		return this.roleCode;
	}

	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}

	@Column(name = "role_description", nullable = false, length = 100)
	public String getRoleDescription() {
		return this.roleDescription;
	}

	public void setRoleDescription(String roleDescription) {
		this.roleDescription = roleDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roleUser")
	public Set<UserApp> getUsers() {
		return this.users;
	}

	public void setUsers(Set<UserApp> users) {
		this.users = users;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "roleUser")
	public RoleFunction getRoleFunction() {
		return this.roleFunction;
	}

	public void setRoleFunction(RoleFunction roleFunction) {
		this.roleFunction = roleFunction;
	}

}
