package com.vince.boot.demo.webapp.entity;
// Generated 28-ago-2017 16.36.04 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TypeDocument generated by hbm2java
 */
@Entity
@Table(name = "d_type_document", uniqueConstraints = @UniqueConstraint(columnNames = "type_code"))
public class TypeDocument extends BaseEntity {	
	private static final long serialVersionUID = 1L;

	private String typeCode;
	private String typeDescription;
	private Set<BlobStore> blobStores = new HashSet<BlobStore>(0);


	public TypeDocument() {
		
	}
	
	public TypeDocument(Long id) {
		this.id=id;
	}

	@Column(name = "type_code", unique = true, nullable = false, length = 20)
	public String getTypeCode() {
		return this.typeCode;
	}

	public void setTypeCode(String typeCode) {
		this.typeCode = typeCode;
	}

	@Column(name = "type_description", nullable = false, length = 100)
	public String getTypeDescription() {
		return this.typeDescription;
	}

	public void setTypeDescription(String typeDescription) {
		this.typeDescription = typeDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeDocument")
	public Set<BlobStore> getBlobStores() {
		return this.blobStores;
	}

	public void setBlobStores(Set<BlobStore> blobStores) {
		this.blobStores = blobStores;
	}

}
